pmp/modules/app-modules/interventions/pages/attachments/components/attachment-dialog.html, pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html
=> Attachments relabel

pmp/modules/app-modules/agreements/data/agreements-list-data.html, pmp/modules/app-modules/agreements/pages/list/agreements-list.html, pmp/modules/app-modules/partners/pages/list/partners-list.html, pmp/modules/mixins/list-filters-mixin.html
=> Filter by special conditions pca

pmp/modules/app-modules/agreements/data/agreements-list-data.html, pmp/modules/app-modules/agreements/pages/list/agreements-list.html
=> Filter by special conditions pca - use dropdown instead of toggle

pmp/modules/app-modules/interventions/pages/details/components/agreement-selector.html
=> Rename to agrement_number_status

pmp/modules/layout/components/etools-status/etools-status.html
=> Fix etools-status style

pmp/modules/app-modules/agreements/agreements-module.html, pmp/modules/layout/components/etools-status/etools-status.html
=> Fix save Special Cond Pca flag

pmp/modules/app-modules/agreements/agreements-module.html, pmp/modules/app-modules/agreements/pages/list/agreements-list.html, pmp/modules/app-modules/interventions/pages/list/interventions-list.html, pmp/modules/app-modules/partners/pages/list/partners-list.html, pmp/modules/layout/components/etools-status/etools-status.html, pmp/modules/mixins/list-filters-mixin.html, pmp/modules/styles/list-filter-styles.html
[ch7942]
Clearing Paper-toggle  doesn't trigger refiltering - this will be dealt with in another task
=> Option to Clear all filter values

pmp/modules/app-modules/interventions/pages/attachments/components/attachment-dialog.html, pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html
=> Pd attachments style tweaks

bower.json, pmp/modules/app-modules/reports/pages/list/reports-list.html
=> fix dropdowns none option style

pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
=> Fix edit assessment

pmp/modules/app-modules/reports/pages/list/reports-list.html
=> Add Clear All filters to Reports list

bower.json, pmp/modules/app-modules/interventions/pages/attachments/components/attachment-dialog.html, pmp/modules/app-modules/partners/pages/financial-assurance/components/assessment-dialog.html
fixed long filename issue ch[9101]
=> removed code that we don't use anymore

pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html, pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
=> Allow 0 in denominator field

pmp/modules/app-modules/reports/pages/list/reports-list.html
fixed default report status options ch[8699]
=> Fix  default report status

pmp/modules/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.html, pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
=> Allow to edit denominator on add indicator

pmp/modules/layout/components/countries-dropdown.html
fixed country label style ch[8597]
=> fixed country label style

bower.json, pmp/modules/mixins/date-mixin.html
fixed filters dropdown not closing issue when clicking the label of another filter ch[9085]
=> Fix  filters dropdown

pmp/modules/mixins/list-filters-mixin.html
=> Fix filters timing issue

pmp/modules/endpoints/endpoints.html
=> Add travel_type filter to Programmatic Visits

pmp/modules/app-modules/agreements/data/agreement-item-data.html, pmp/modules/app-modules/mixins/module-common-mixin.html
=> Fix agreeement_number_status missing from agr selector on PD

pmp/modules/layout/menu/app-sidebar-menu.html
=> Updates info link on sidebar

pmp/modules/layout/page-header.html
=> Changes logout link to /logout

bower.json
=> Updates app-selector to v2.1.9

package-lock.json, package.json, src/components/mixins/date-mixin.ts, src/components/mixins/frontend-pagination-mixin.ts, src/components/mixins/missing-dropdown-options-mixin.ts
missing-dropdown-options-mixin, frontend-pagination-mixin, date-mixin
=> Mixin migrations

package-lock.json, src/components/app-modules/partners/pages/overview/partner-overview.ts
=> Partner overview migration

pmp/modules/app-modules/agreements/data/agreement-item-data.html, pmp/modules/app-modules/partners/data/partner-item-data.html, pmp/modules/user/profile-operations-mixin.html
adjusted toast message and removed closeButton [ch4846]
=> adjusted toast message and removed closeButton

pmp/modules/app-modules/interventions/pages/details/intervention-details.html, pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
renamed programmatic visits tab [ch7641]
=> renamed tab title

pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html, pmp/modules/app-modules/interventions/pages/details/components/results/mixins/indicators-common-mixin.html, pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
=> restrict baseline values to numbers

pmp/modules/app-modules/interventions/data/interventions-list-data.html, pmp/modules/app-modules/interventions/pages/list/interventions-list.html
added endsAfter filter on interventions list [ch9577]
=> added endsAfter filter on interventions list

package-lock.json, src/components/app-modules/interventions/data/interventions-list-data.ts, src/components/app-modules/interventions/pages/list/interventions-list.ts
added endAfter filter on interventions list
=> added endAfter filter on interventions list

bower.json
@adi130987 Nik asked for this update to be included in the push to production happening tomorrow morning, New York time. It's just a change to the url of the piwik tracker.
=> Updates etools-piwik-analytics to v2.0.2

package-lock.json, src_ts/components/app-modules/interventions/pages/details/components/results/result-cp-output-and-ram-indicators.ts, src_ts/components/app-modules/interventions/pages/details/components/results/result-link-lower-results.ts
title and labels adjustments ch[5404]
=> Labels consistency on pd details [polymer 3]

pmp/modules/app-modules/interventions/pages/details/intervention-details.html
Allow Planned Visits to extend 1 year past PD end date ch[4326]
=> Allow Planned Visits to extend 1 year past PD end date [polymer 2]

pmp/modules/user/user-permissions-mixin.html
adjusted unicef user permissions ch[9368]
=> adjusted unicef user permissions

src_ts/components/app-modules/interventions/pages/details/components/results/result-cp-output-and-ram-indicators.ts
change add/update cp dialog label
=> Fix  title labels

package-lock.json, src_ts/components/app-modules/interventions/data/intervention-item-data.ts, src_ts/components/app-modules/interventions/interventions-module.ts
"i am done" button will not save any edited fields ch[5886]
=> Fix  amendment mode

src_ts/components/app-shell/header/page-header.ts, src_ts/config/config.ts
=> Adds env warning for all remaining environments

package-lock.json, src_ts/components/app-modules/interventions/components/pd-termination.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.ts, src_ts/components/layout/etools-warn-message.ts
changed PD amendment types and corresponding messages ch[9967]
=> Feature  pd amendment types

pmp/modules/config/config.html, pmp/modules/layout/page-header.html
=> Adds header environment warnings to remaining envs

pmp/modules/config/config.html
=> Fixes _checkEnvironment call in config

index.html, pmp/modules/layout/components/support-btn.html, pmp/modules/layout/page-header.html
=> [PROD] Support button

gulpfile.js, src_ts/components/app-modules/interventions/pages/details/intervention-details.ts, src_ts/components/endpoints/endpoints.ts, src_ts/components/styles/buttons-styles.ts
=> Export expected results

src_ts/components/mixins/lists-common-mixin.ts
=> Fix lists export

src_ts/components/app-modules/interventions/pages/overview/intervention-overview.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/layout/monitoring-visits-list.ts
=> Show TPM visits in PD overview

src_ts/components/app-shell/menu/app-menu.ts
=> Fix Reports, Settings visibility when prp_mode_off

src_ts/components/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.ts, src_ts/components/app-shell/app-theme.ts
=> 10675 polymer 3 migration issues

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/details/components/results/mixins/results-mixin.ts, src_ts/components/app-modules/interventions/pages/overview/intervention-overview.ts, src_ts/components/mixins/repeatable-data-sets-mixin.ts
=> Fix PD overview/cp outputs sync with pd details changes

src_ts/components/app-modules/interventions/pages/details/intervention-details.ts
=> Style updates for Results export btn

src_ts/components/app-modules/partners/pages/financial-assurance/components/assessment-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/app-modules/partners/partners-module.ts
=> Update basis for risk rating after assessment changes

src_ts/components/app-modules/reports/pages/list/reports-list.ts
=> Fix report_Type not being cleared from url on click Clear All

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/attachments/intervention-attachments.ts, src_ts/components/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/components/fund-reservations/fund-reservations.ts, src_ts/components/app-modules/partners/components/partner-status.ts
=> ch[11244] dynamic dialog mixin

src_ts/components/app-modules/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/app-modules/interventions/pages/details/components/results/applied-indicators.ts, src_ts/components/app-modules/interventions/pages/details/components/results/result-link-lower-results.ts, src_ts/components/app-modules/partners/data/partner-item-data.ts
=> Fix empty _deleteEpName

src_ts/components/app-modules/interventions/pages/attachments/intervention-attachments.ts
=> Fix PD attachments refresh

package-lock.json, src_ts/components/app-modules/reports/pages/list/reports-list.ts, src_ts/components/app-modules/reports/reports-module.ts
=> Fix reports export

src_ts/components/app-modules/agreements/pages/details/agreement-details.ts, src_ts/components/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.ts, src_ts/components/app-modules/agreements/pages/list/agreements-list.ts, src_ts/components/app-modules/interventions/components/pd-termination.ts, src_ts/components/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.ts, src_ts/components/app-modules/interventions/pages/details/intervention-details.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessment-dialog.ts, src_ts/config/config.ts
=> Update datepicker selected date display

package-lock.json, src_ts/components/app-modules/reports/components/report-reject-dialog.ts, src_ts/components/app-modules/reports/mixins/report-details-mixin.ts, src_ts/components/app-modules/reports/pages/progress/components/sr-details.ts, src_ts/components/app-modules/reports/pages/summary/report-summary.ts, src_ts/components/app-modules/reports/reports-module.ts, src_ts/components/endpoints/endpoints.ts
=> Update PRP Report attachments

src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts, src_ts/components/app-modules/reports/components/report-rating-dialog.ts
=> Update Reports progress percentage

src_ts/components/app-modules/partners/pages/details/partner-details.ts
[ch11408] PMP CSS and HTML issues
=> [ch11408] PMP CSS and HTML issues

src_ts/components/layout/etools-cp-structure.ts, src_ts/components/layout/etools-error-messages-box.ts, src_ts/components/layout/etools-form-element-wrapper.ts, src_ts/components/layout/etools-progress-bar.ts, src_ts/components/layout/etools-ram-indicators.ts, src_ts/components/layout/etools-status/etools-action-button.ts, src_ts/components/layout/etools-status/etools-status.ts, src_ts/components/layout/etools-tabs.ts, src_ts/components/layout/etools-warn-message.ts, src_ts/components/layout/icons-actions.ts, src_ts/components/layout/monitoring-visits-list.ts, src_ts/components/layout/page-content-header.ts, src_ts/components/layout/year-dropdown.ts
[ch11345] Add polymer decorators - `layout` folder
=> [ch11345]  Add polymer decorators - `layout` folder

src_ts/components/app-modules/interventions/pages/details/components/results/indicator-dissaggregations.ts, src_ts/reducers/common-data.ts
=> Flag inactive disaggregations 

package-lock.json, src_ts/components/app-shell/app-shell.ts
[ch11403] 'Loading..' message and backdrop to not enclose whole page
=> [ch11403] 'Loading..' message and backdrop to not enclose whole page

src_ts/components/app-shell/footer/page-footer.ts, src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/data-refresh-dialog.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/toast-notifications/etools-toast.ts, src_ts/components/user/profile-operations-mixin.ts
[ch11922] Add missing @property decorators
=> [ch11922] Add missing @property decorators

src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts
=> Fix date conversion

src_ts/components/app-modules/partners/pages/details/partner-details.ts
[ch12239] Partner Page Core Values Assessment Toast Notification
=> [ch12239] Partner Page Core Values Assessment Toast Notification

src_ts/components/app-modules/partners/pages/list/partners-list.ts
[ch12555] Disable CSO Type filter from Government page
=> [ch12555] Disable CSO Type filter from Government page

src_ts/components/app-modules/reports/pages/progress/components/indicator-details.ts
[ch12524] Style issue on Report Progress
=> [ch12524] Style issue on Report Progress 

src_ts/components/app-modules/interventions/mixins/intervention-permissions-mixin.ts, src_ts/components/app-modules/interventions/mixins/save-intervention-mixin.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.ts
[ch12696] Make the "PD Submission Date" a mandatory field for transition to Signed
=> [ch12696] Make the "PD Submission Date" a mandatory field for transition to Signed

package.json
=> Updates etools-profile-dropdown to v4.0.1-rc.1

package-lock.json, src_ts/components/app-shell/app-shell-styles.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/app-drawer-styles.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts
=> remove use of dom-module from styles

package-lock.json, package.json, src_ts/components/app-shell/header/page-header.ts
=> Upgrades app-selector to v3.0.0-rc.2

src_ts/components/app-modules/interventions/data/interventions-list-data.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts
[ch12424] Add Partner multi-select filter for PD/SSFA
=> [ch12424] Add Partner multi-select filter for PD/SSFA

package-lock.json, src_ts/components/app-modules/interventions/pages/details/components/planned-visits.ts, src_ts/components/app-modules/interventions/pages/details/intervention-details.ts, src_ts/components/endpoints/endpoints.ts, src_ts/components/mixins/repeatable-data-sets-mixin.ts
[ch11545] Allow deletion of a PV visit row in Draft
=> [ch11545] Allow deletion of a PV visit row in Draft

src_ts/components/app-modules/reports/pages/summary/report-summary.ts
[ch13520] Challenges is misspelled
=> [ch13520] Challenges is misspelled

src_ts/components/app-modules/interventions/pages/details/components/results/applied-indicator.ts
[ch13200] [PRP] Indicator icon (#, %, ratio) - make it stand out a bit more
=> [ch13200] [PRP] Indicator icon (#, %, ratio) - make it stand out a bit more

src_ts/components/app-modules/interventions/data/interventions-list-data.ts, src_ts/components/app-modules/interventions/pages/details/components/planned-visits.ts, src_ts/components/app-modules/interventions/pages/details/components/results/non-cluster-indicator.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-modules/partners/pages/details/components/add-edit-staff-members.ts, src_ts/components/endpoints/endpoints.ts, src_ts/components/mixins/repeatable-data-sets-mixin.ts
[ch13202] Add an option to "add all locations" on the indicator modal
Fixed formatting (removed extra spaces)
=> [ch13202] Add an option to "add all locations" on the indicator modal

src_ts/components/app-modules/reports/pages/progress/report-progress.ts, src_ts/components/app-modules/reports/pages/summary/report-summary.ts
[ch13521] No Attachment shows up in PMP for Special Reports
=> [ch13521] No Attachment shows up in PMP for Special Reports

package-lock.json, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts
=> display last assessment date

src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts
=> [ch13690]Fix financial progress

src_ts/components/app-modules/reports/components/report-rating-dialog.ts
[ch7287] No rating for SR report type
=> [ch7287] No rating for SR report type

src_ts/components/layout/etools-ram-indicators.ts
[ch15213] Error viewing Progress tab from PD/SSFA
=> [ch15213] Error viewing Progress tab from PD/SSFA

src_ts/components/app-shell/app-shell.ts
[ch15627] 'Burger' button doesn't work constantly
=> [ch15627] 'Burger' button doesn't work constantly

src_ts/components/app-modules/agreements/pages/details/agreement-details.ts
fixed generate PCA hover button issue
=> [ch16135] Pointer cursor not present on 'Generate' btn

src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts
=> [ch13690]Handle progress endpoint returning 404

src_ts/components/app-modules/interventions/pages/details/components/results/indicator-dissaggregations.ts
hide add button if maximum number of disaggregations is met
=> [ch16163] Limit the number of disaggregations

src_ts/components/app-modules/partners/pages/details/components/add-edit-staff-members.ts
increased partner contact possition char limit to 100
=> [ch15125] Character limitation in PMP when adding partner title

src_ts/components/app-modules/partners/components/new-partner-dialog.ts, src_ts/components/app-modules/reports/components/report-rating-dialog.ts, src_ts/components/app-modules/reports/components/report-reject-dialog.ts
[ch16260] Unnecessary vertical scroll bar in dialog
fixed dialog vertical scroll issue
=> [ch16260] Unnecessary vertical scroll bar in dialog

src_ts/components/app-modules/reports/pages/progress/components/sr-details.ts, src_ts/components/app-modules/reports/pages/summary/report-summary.ts
[ch16257] No space between displayed uploaded files
fix report file attachment file name margin
=> [ch16257] No space between displayed uploaded files

src_ts/components/app-modules/reports/pages/progress/components/report-overall.ts, src_ts/components/app-modules/reports/pages/progress/report-progress.ts
[ch16198] Spelling issues in Results reported
fixed spelling issue
=> [ch16198] Spelling issues in Results reported

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.ts
[ch16442] Status section jumps to the bottom of the page
=> [ch16442] Status section jumps to the bottom of the page

package.json, src_ts/actions/app.ts, src_ts/components/app-modules/agreements/pages/details/agreement-details.ts, src_ts/components/app-modules/interventions/pages/details/components/planned-visits.ts, src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/app-modules/reports/components/report-rating-dialog.ts, src_ts/components/app-shell/app-shell.ts, src_ts/components/layout/monitoring-visits-list.ts, src_ts/reducers/app.ts
[ch15768] Fix lint errors
fixed eslint errors
=> [ch15768] Fix lint errors

src_ts/components/app-modules/interventions/pages/details/intervention-details.ts, src_ts/components/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.ts, src_ts/components/styles/page-layout-styles.ts
General layout fix to prevent page content to grow and to push Status section at the bottom of the page
=> General layout fix to prevent page content to grow and to push Status

package.json, src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/layout/support-btn.ts
[ch17296] Responsive app header
=> [ch17296] Responsive app header

package-lock.json, src_ts/components/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.ts
[ch17182] At save the submitted to PRC checkbox is unchecked, Submission date, Review Date and PRC review doc are hidden
=> [ch17182] At save the submitted to PRC checkbox is unchecked, Submission date, Review Date and PRC review doc are hidden

package-lock.json, package.json
=> Upgrades app selector to 3.1.3

src_ts/components/app-shell/app-shell.ts
[ch17769] Left side menu disappears
=> [ch17769] Left side menu disappears

package-lock.json, package.json
[ch16003] Dropdown Search not tied to search input
=> [ch16003] Dropdown Search not tied to search input

src_ts/components/app-modules/agreements/pages/list/agreements-list.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-modules/partners/pages/list/partners-list.ts
=> [ch17817]List links issue on mobile

src_ts/components/app-modules/reports/components/report-rating-dialog.ts
[ch7287] No rating for SR report type
=> [ch7287] No rating for SR report type, [ch18132] Special Report: Accept report btn with no action

src_ts/components/app-modules/agreements/pages/details/components/amendments/agreement-amendments.ts
=> Fix amendment template download

src_ts/components/app-modules/partners/pages/financial-assurance/components/hact-edit-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/styles/grid-layout-styles.ts
=> [ch18190]Ability to edit hact values

src_ts/components/app-modules/reports/pages/progress/components/indicator-details.ts
[ch18990] Incorrect display of location progress in QPR and HR
=> [ch18990] Incorrect display of location progress in QPR and HR

src_ts/components/app-modules/partners/pages/financial-assurance/components/hact-edit-dialog.ts
[ch19270] Error display issue [object object] on Partner Financial info editing
=> [ch19270] Error display issue [object object] on Partner Financial info editing

src_ts/components/layout/etools-form-element-wrapper.ts
[ch13522] Add N/A for Special Reports
[ch16608] Reports: Other Info tab available for Humanitarian reports, but missing in Partner Reporting Portal
=> [ch13522] Add N/A for Special Reports, [ch16608] Reports: Other Info tab available for Humanitarian reports, but missing in Partner Reporting Portal

src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/models/partners.models.ts
[ch17999] Add PSEA Risk rating to Assurance tab
=> [ch17999] Add PSEA Risk rating to Assurance tab

src_ts/components/app-modules/partners/pages/overview/partner-overview.ts
[ch17998] PSEA - Partner Overview
=> [ch17998] PSEA - Partner Overview

src_ts/components/app-modules/partners/pages/details/partner-details.ts
[ch18001] PSEA Partner details update
=> [ch18001] PSEA Partner details update

src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts, src_ts/components/app-modules/reports/pages/progress/components/indicator-details.ts
=> [ch16433]Fix progress percentage

src_ts/components/app-modules/partners/pages/list/partners-list.ts
=> [ch18002]Show PSEA rating&date on Partner list

src_ts/components/app-modules/interventions/pages/details/components/results/applied-indicators.ts, src_ts/components/utils/ajax-errors-parser.ts
[ch18194]Deactivate Cluster indicator error
=> [ch18194]Deactivate Cluster indicator error

src_ts/components/mixins/risk-rating-mixin.ts
adjustments for new sea status
=> adjustments for new sea status

src_ts/components/app-modules/agreements/agreements-module.ts, src_ts/components/app-modules/agreements/data/agreement-item-data.ts, src_ts/components/app-modules/agreements/data/agreement-termination.ts, src_ts/components/app-modules/agreements/pages/components/agreement-status.ts, src_ts/components/app-modules/agreements/pages/details/agreement-details.ts, src_ts/components/layout/etools-status/etools-action-button.ts
[ch17886]Add a Termination letter for termination of PCA
=> [ch17886]Add a Termination letter for termination of PCA

src_ts/components/mixins/risk-rating-mixin.ts
=> [ch20228]Fix undefined err

src_ts/actions/common-data.ts, src_ts/components/app-modules/partners/data/partners-list-data.ts, src_ts/components/app-modules/partners/pages/list/partners-list.ts, src_ts/components/common-data-mixins/common-data.ts, src_ts/reducers/common-data.ts
[ch19915]
Waiting for bk fixes
=> [ch19915]PSEA filters

src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts
[ch20400] Misaligned 'Basis for Risk Rating' dropdown
=> [ch20400] Misaligned 'Basis for Risk Rating' dropdown

src_ts/components/app-modules/reports/components/reports-display-list.ts, src_ts/components/mixins/list-data-mixin.ts
=> [ch20568]Replace ajax mixin in reports-display-list

package-lock.json, package.json, src_ts/components/mixins/ajax-server-errors-mixin.ts
[ch20688] Lingering toast message issue
=> [ch20688] Lingering toast message issue

src_ts/components/app-modules/interventions/pages/review-and-sign/components/fund-reservations/fund-reservations.ts
[ch20760] Cannot add multiple FR numbers
=> [ch20760] Cannot add multiple FR numbers

src_ts/components/app-modules/interventions/data/interventions-list-data.ts, src_ts/components/app-modules/interventions/pages/details/intervention-details.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/typings/intervention.types.ts
[ch16659] Add contingency filter in PD/SSFA
=> [ch16659] Add contingency filter in PD/SSFA

src_ts/components/app-modules/reports/reports-module.ts
[ch21432] Status says no status when a report is sent back to partner
=> [ch21432] Status says no status when a report is sent back to partner

src_ts/components/app-modules/reports/reports-module.ts
[ch7973] Report Page Indicator Export
=> [ch7973] Report Page Indicator Export

package-lock.json, package.json, src_ts/components/app-modules/agreements/agreements-module.ts, src_ts/components/app-modules/interventions/data/intervention-item-data.ts, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.styles.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts, src_ts/components/app-modules/mixins/module-routing-mixin.ts, src_ts/components/app-modules/partners/partners-module.ts, src_ts/components/app-modules/reports/reports-module.ts, src_ts/components/styles/column-styles.ts, src_ts/typings/agreement.types.ts, src_ts/typings/globals.types.ts, src_ts/typings/partner.types.ts
[ch21178]
Points to discuss:
1) Some fields are not existed on backend side - card for this is already added
2) We need some helper methods for getting endpoints (for sendRequest method) - now this logic is implemented in Polymer Mixin and it is not applicable to Lit Elements
3) Validation - for now I leave only backend validation
=> [ch21178]New PD page

src_ts/components/app-modules/agreements/pages/details/agreement-details.ts, src_ts/components/app-modules/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/app-modules/agreements/pages/list/agreements-list.ts, src_ts/components/app-modules/interventions/pages/details/intervention-details.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts
[ch21742] Consistent reference number labels in PMP
=> [ch21742] Consistent reference number labels in PMP

package.json, src_ts/reducers/common-data.ts
=> [ch22179]Hanging in loading state

src_ts/components/app-shell/app-theme.ts
[ch22116] Dividers are invisible in PMP (style issue)
=> [ch22116] Dividers are invisible in PMP (style issue)

src_ts/actions/common-data.ts, src_ts/components/common-data-mixins/common-data.ts, src_ts/reducers/common-data.ts
[ch22181] Gender-equity-rating tweaks/bk needs
=> [ch22181] Gender-equity-rating tweaks/bk needs

src_ts/components/app-shell/app-theme.ts
[ch22214] Align content-panel title to the left
=> [ch22214] Align content-panel title to the left

src_ts/actions/common-data.ts, src_ts/components/common-data-mixins/common-data.ts, src_ts/reducers/common-data.ts
[ch22186] Risks component tweaks/bk needs
=> [ch22186] Risks component tweaks/bk needs

src_ts/components/app-shell/app-theme.ts
[ch22299] Gray overwriting by black in content-panel
=> [ch22299] Gray overwriting by black in content-panel

src_ts/components/app-modules/interventions/pages/details/intervention-details.ts
[ch22492] Rename CFEI label in PD
=> [ch22492] Rename CFEI label in PD

polymer.json
=> [ch22388]Fix redirect to 404 when accessing create pd page

src_ts/components/app-modules/interventions/data/intervention-item-data.ts, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts, src_ts/typings/intervention.types.ts
=> [ch22499]Fix create intervention

src_ts/components/app-modules/interventions/data/intervention-item-data.ts, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts, src_ts/components/utils/date-utils.ts, src_ts/components/utils/utils.ts, src_ts/typings/intervention.types.ts
=> [ch22558]Reset form on cancel create PD

src_ts/actions/common-data.ts, src_ts/components/common-data-mixins/common-data.ts, src_ts/reducers/common-data.ts
[ch22167]PD Management - Financial component tweaks/bk needs
=> [ch22167]PD Management - Financial component tweaks/bk needs

src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
=> [ch22686]Fix save agreement on intervention

src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/mixins/common-mixin.ts
[ch22503] Update intervention status (Draft to Development)
=> [ch22503] Update intervention status (Draft to Development)

src_ts/components/app-shell/app-shell.ts, src_ts/components/utils/router.ts
[ch22337] Reflect Comment mode in url
=> [ch22337] Reflect Comment mode in url

src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
[ch22732] Create PD- remove SSFA doc type from dropdown
=> [ch22732] Create PD- remove SSFA doc type from dropdown

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-shell/menu/app-menu.ts
[ch22842]Rename SSFA labels from PMP
=> [ch22842]Rename SSFA labels from PMP

polymer.json
[ch22837] PMP- 404 on accessing Progress, Reports tabs
=> [ch22837] PMP- 404 on accessing Progress, Reports tabs

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/mixins/module-common-mixin.ts
[ch22824] Loading spinner not shown when going to PD details from list
=> [ch22824] Loading spinner not shown when going to PD details from list

package-lock.json, package.json
[ch22787]Text color on Save btn in dialog
=> [ch22787]Text color on Save btn in dialog

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-shell/app-theme.ts
=> [ch22423]Update etools-content-panel header text style

package-lock.json, package.json, src_ts/components/app-shell/app-theme.ts
[ch22456] Results tab - Collapse icons have become blue issue
=> [ch22456] Results tab - Collapse icons have become blue issue

src_ts/components/mixins/list-filters-mixin.ts
[ch23108] Clear all filters no action on Search input
=> [ch23108] Clear all filters no action on Search input

package-lock.json, package.json
[ch22928]File type validation on etools-upload not working
=> [ch22928]File type validation on etools-upload not working

src_ts/components/app-modules/agreements/pages/details/agreement-details.ts
[ch23126] On Create Agreement - remove SSFA option from Agreement type dropdown
=> [ch23126] On Create Agreement - remove SSFA option from Agreement type dropdown

src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/mixins/common-mixin.ts, src_ts/typings/intervention.types.ts
[ch23125]Show 'Accepted/Sent to' on the interventions list
=> [ch23125]Show 'Accepted/Sent to' on the interventions list

src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
=> [ch22448]Tweak styles for add pd form

src_ts/components/endpoints/endpoints.ts
=> [ch23494]Update sections endpoint to v3

src_ts/components/app-shell/header/page-header.ts
[ch23380] Countries drop-down too close to languages drop-down
=> [ch23380] Countries drop-down too close to languages drop-down

src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/mixins/common-mixin.ts
[ch23497] Status display issue on List using Search
=> [ch23497] Status display issue on List using Search

package-lock.json, package.json
=> [ch23100]Update etools-dialog v

src_ts/components/app-modules/interventions/pages/overview/components/fund-reservations-display.ts
[ch23544] PD Implementation Status/ Improve external-icon display
=> [ch23544] PD Implementation Status/ Improve external-icon display

src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
=> [ch23651]Fix reference years

src_ts/components/app-modules/mixins/module-common-mixin.ts, src_ts/components/app-modules/mixins/module-routing-mixin.ts
Removed references to missing files
=> Removed references to missing files

src_ts/typings/intervention.types.ts
[ch23624] UNPP CFEI/DSR Ref Number should be editable on add new PD
=> [ch23624] UNPP CFEI/DSR Ref Number should be editable on add new PD

src_ts/components/app-shell/app-shell.ts
[ch23743] Intermittent: Missing translations
=> [ch23743] Intermittent: Missing translations

src_ts/components/app-modules/interventions/data/interventions-list-data.ts
=> [ch23127]Fix filter by CP Structures

src_ts/components/mixins/common-mixin.ts
=> [ch23513]Replace date_draft_by_partner with submission_date

src_ts/components/app-modules/interventions/pages/list/interventions-list.ts
[ch20495] Some list filters don't work [Ends after, Donor and Grant]
=> [ch20495] Some list filters don't work [Ends after, Donor and Grant]

src_ts/config/config.ts
=> [ch22210]Refactor config file

src_ts/components/app-modules/reports/pages/summary/report-summary.ts, src_ts/components/mixins/common-mixin.ts
[ch22122] New Field in PRP for "CSO financial contribution"
=> [ch22122] New Field in PRP for "CSO financial contribution"

src_ts/components/app-modules/agreements/data/agreement-item-data.ts
=> [ch23915]Fix CP Structure not selected automatically for a recently created Agreement

src_ts/components/app-modules/agreements/data/agreement-item-data.ts, src_ts/components/mixins/common-mixin.ts
=> [ch23919]Fix sentto appearing on other statuses

src_ts/actions/common-data.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/endpoints/endpoints-mixin.ts, src_ts/components/user/profile-operations-mixin.ts, src_ts/components/user/user-data-mixin.ts, src_ts/reducers/common-data.ts
[ch22180] Technical Debt - user in 2 different nodes in redux store
=> [ch22180] Technical Debt - user in 2 different nodes in redux store

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts
[ch23781] Add second language (romanian).
=> [ch23781] Add second language (romanian).

.circleci/config.yml, polymer.json
=> [ch24107]CI config

src_ts/components/app-modules/interventions/data/interventions-list-data.ts
[ch22493] PD/SSFA List add CFEI search
=> [ch22493] PD/SSFA List add CFEI search

src_ts/components/app-modules/interventions/data/interventions-list-data.ts
=> [ch24364]Undo search by cfei

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
[ch23781] Add second language (romanian).
=> [ch23781] Additions for translations(new intervention page + list filters) 

src_ts/components/mixins/common-mixin.ts
[ch24430] ePD: "Unicef" should be "UNICEF" across entire application
=> [ch24430] ePD: "Unicef" should be "UNICEF" across entire application

src_ts/components/app-modules/agreements/pages/list/agreements-list.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-modules/partners/pages/list/partners-list.ts, src_ts/components/app-modules/reports/pages/list/reports-list.ts, src_ts/components/mixins/list-filters-mixin.ts
=> [ch24406]'Clear all' to clear filters also not just their selected values

src_ts/components/app-modules/partners/pages/financial-assurance/components/assessments-items.ts
[ch24388] Migrate remaining intervention-tab-pages PolymerElements to LitElement
=> [ch24388] Migrate remaining intervention-tab-pages PolymerElements to LitElement

src_ts/components/app-modules/agreements/data/agreement-termination.ts, src_ts/components/app-modules/interventions/data/intervention-item-data.ts, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/mixins/intervention-page-tabs-mixin.ts, src_ts/components/app-modules/settings/components/disaggregation-list.ts, src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common-data-mixins/common-data.ts, src_ts/components/environment-flags/environment-flags-mixin.ts, src_ts/components/environment-flags/environment-flags.ts
[ch24635]Multiple global declarations of element-mixin with identifier EnvironmentFlagsMixin
=> [ch24635]Multiple global declarations of element-mixin with identifier EnvironmentFlagsMixin

src_ts/components/app-modules/partners/components/new-partner-dialog.ts, src_ts/components/app-modules/partners/pages/details/components/add-edit-staff-members.ts, src_ts/components/app-modules/partners/pages/details/components/edit-core-values-assessment.ts, src_ts/components/app-modules/partners/pages/details/components/staff-members.ts, src_ts/components/app-modules/partners/pages/details/partner-details.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessment-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/hact-edit-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/app-modules/partners/partners-module.ts, src_ts/components/utils/dialog.ts
[ch24756] [Refactor] Simplify how modals are used (Partners menu)
=> [ch24756] [Refactor] Simplify how modals are used (Partners menu)

src_ts/components/app-modules/interventions/data/interventions-list-data.ts
[ch24651] Console error when using Search
=> [ch24651] Console error when using Search

src_ts/components/app-modules/reports/pages/progress/components/disaggregations/styles/disaggregation-table-styles.ts, src_ts/components/app-shell/app-shell-styles.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts, src_ts/components/layout/etools-status/etools-status-styles.ts, src_ts/components/layout/page-content-header-slotted-styles.ts, src_ts/components/styles/app-mixins.ts, src_ts/components/styles/buttons-styles.ts, src_ts/components/styles/grid-layout-styles.ts, src_ts/components/styles/list-filter-styles.ts, src_ts/components/styles/partner-status-styles.ts, src_ts/components/styles/repeatable-data-sets-styles.ts, src_ts/components/styles/required-field-styles.ts, src_ts/components/styles/risk-rating-styles.ts
[ch24690][Refactor] Drop the use of iron-flex-layout -  Styles files
=> [ch24690][Refactor] Drop the use of iron-flex-layout -  Styles files

src_ts/components/app-modules/reports/components/report-status.ts, src_ts/components/app-modules/reports/pages/list/reports-list.ts, src_ts/components/app-modules/reports/pages/progress/components/indicator-report-target.ts, src_ts/components/app-modules/reports/pages/progress/report-progress.ts, src_ts/components/app-modules/reports/pages/summary/report-summary.ts, src_ts/components/layout/etools-cp-structure.ts, src_ts/components/layout/etools-error-messages-box.ts, src_ts/components/layout/etools-progress-bar.ts, src_ts/components/layout/etools-status/etools-action-button.ts, src_ts/components/layout/etools-tabs.ts, src_ts/components/layout/page-content-header.ts
[ch24690][Refactor] Drop the use of iron-flex-layout - Styles Files
=> [ch24690][Refactor] Drop the use of iron-flex-layout - Styles Files

src_ts/components/app-modules/agreements/data/agreement-termination.ts, src_ts/components/app-modules/agreements/pages/components/agreement-status.ts, src_ts/components/app-modules/agreements/pages/details/agreement-details.ts, src_ts/components/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.ts, src_ts/components/app-modules/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/app-modules/agreements/pages/details/components/generate-PCA-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessment-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/hact-edit-dialog.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts
[ch24782] [Refactor] Simplify how modals are used (Agreements menu)
=> [ch24782] [Refactor] Simplify how modals are used (Agreements menu)

src_ts/components/app-modules/reports/components/report-rating-dialog.ts, src_ts/components/app-modules/reports/components/report-reject-dialog.ts, src_ts/components/app-modules/reports/pages/summary/report-summary.ts, src_ts/components/app-modules/reports/pages/summary/sent-bk-comments.ts, src_ts/components/app-modules/reports/reports-module.ts, src_ts/components/app-modules/settings/components/add-disaggregation-dialog.ts, src_ts/components/app-modules/settings/components/disaggregation-list.ts
[Refactor] Simplify how modals are used (Reports and Settings menu)
=> [Refactor] Simplify how modals are used (Reports and Settings menu)

src_ts/components/app-modules/agreements/pages/details/agreement-details.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/partners/pages/details/components/edit-core-values-assessment.ts, src_ts/components/app-modules/partners/pages/details/components/staff-members.ts, src_ts/components/app-modules/partners/pages/details/partner-details.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/app-modules/reports/pages/progress/components/indicator-report-target.ts, src_ts/components/app-modules/reports/pages/progress/components/report-overall.ts, src_ts/components/app-modules/reports/pages/progress/components/sr-details.ts, src_ts/components/app-modules/reports/pages/progress/report-progress.ts, src_ts/components/app-modules/reports/pages/summary/report-summary.ts, src_ts/components/app-modules/reports/pages/summary/sent-bk-comments.ts, src_ts/components/layout/etools-form-element-wrapper.ts, src_ts/components/layout/icons-actions.ts, src_ts/components/layout/monitoring-visits-list.ts
=> [ch24828] Fix layout issues

index.html, package-lock.json, package.json, polymer.json, src_ts/config/config.ts
=> [ch24812]Safari focus visible

src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
[ch25166] Hide partner staff members in Add New PD
=> [ch25166] Hide partner staff members in Add New PD

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
[ch25170] Remove toggle "I Have UNPP Number"
=> [ch25170] Remove toggle "I Have UNPP Number"

src_ts/components/mixins/common-mixin.ts
=> [ch25176]Relabel IP Accepted & localize

src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
[ch25175] On Add New PD, show start and end date fields
=> [ch25175] On Add New PD, show start and end date fields

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
[ch25168] PMP Add new PD - Document Partner Focal Points tooltip
=> [ch25168] PMP Add new PD - Document Partner Focal Points tooltip

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
=> [ch25145]validation in CFEI/DSR field in PMP

src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts, src_ts/components/app-modules/partners/pages/financial-assurance/components/hact-edit-dialog.ts, src_ts/components/app-shell/app-shell.ts, src_ts/components/layout/etools-status/etools-status-common-mixin.ts, src_ts/components/mixins/list-filters-mixin.ts, src_ts/components/mixins/repeatable-data-sets-mixin.ts
[ch25234] Cancel on Add PD does not restore the default Document Currency value
=> [ch25234] Cancel on Add PD does not restore the default Document Currency value

src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
=> [ch25145]Tweak validation

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
[ch25297] Rearrange fields on 'Add New PD' Page
=> [ch25297] Rearrange fields on 'Add New PD' Page

src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts
=> [ch25386]Fix Min Requirement not showing

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.ts
=> [ch25424]Fix-On new PD page, validation message overlaps label below

src_ts/components/app-modules/partners/pages/overview/partner-overview.ts
=> [ch25386]Fix programmatic_visits property name

package-lock.json, package.json, src_ts/components/styles/list-filter-styles.ts
[ch25677] Fix filters dropdown short flash of the scrollbar at opening
=> [ch25677] Fix filters dropdown short flash of the scrollbar at opening

src_ts/components/app-modules/interventions/pages/progress/intervention-progress.ts, src_ts/components/utils/date-utils.ts
[ch25684] PMP: PROGRESS tab show incorrect "PD Duration" and "Cash Transfered" values
=> [ch25684] PMP: PROGRESS tab show incorrect "PD Duration" and "Cash Transfered" values

package-lock.json, package.json, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
[ch25809] Multi selection dropdown style improvements
[ch25785] Invalid message displayed premature at dialog open
=> [ch25809] Multi selection dropdown style improvements, [ch25785] Invalid message displayed premature at dialog open

src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts
=> [ch25895]Show arrow to the rigth when left side menu is minimized

src_ts/components/app-modules/interventions/pages/new/info-icon-tooltip.ts, src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
=> [ch25862]Info icon tooltip- handle smaller screen width text wrap

src_ts/components/app-modules/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/app-modules/partners/pages/financial-assurance/partner-financial-assurance.ts
[ch25926] Partner Assurance - 'Other Assessments' table cut off
=> [ch25926] Partner Assurance - 'Other Assessments' table cut off

package-lock.json, package.json
=> [ch25921] Update etools-date-time

src_ts/components/app-modules/agreements/pages/list/agreements-list.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts, src_ts/components/app-modules/partners/pages/list/partners-list.ts, src_ts/components/app-modules/reports/components/reports-display-list.ts
[ch26023] Localization in polymer 3 for table on small screen width not working
=> [ch26023] Localization in polymer 3 for table on small screen width not working

package-lock.json, package.json
=> (epd)[ch25846]Update app-selector 

src_ts/components/app-modules/interventions/data/intervention-item-data.ts
=> [ch26126]Error on list filtering after adding a new PD

src_ts/components/app-modules/interventions/data/intervention-item-data.ts
=> [ch25932]Update list on intervention status change

polymer.json, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/mixins/module-routing-mixin.ts
=> [ch26224]ePD changes

package-lock.json, package.json
[ch26218] Restyle datepicker control
=> [ch26218] Restyle datepicker control

src_ts/components/mixins/utils-mixin.ts
[ch26119] Progress report in eTools does not show percentages correctly
=> [ch26119] Progress report in eTools does not show percentages correctly

src_ts/components/app-modules/agreements/pages/list/agreements-list.ts, src_ts/components/app-modules/interventions/pages/list/interventions-list.ts
=> [ch26351]PD and Agreements list add Partner to default filters

.gitmodules, package-lock.json, package.json, src_ts/components/app-modules/interventions/interventions-module.ts
=> [ch26373]Use common package

package-lock.json, package.json
=> [ch26374]Update etools-date-time

src_ts/components/app-modules/interventions/data/intervention-item-data.ts, src_ts/components/app-modules/interventions/interventions-module.ts
[ch26659] Amendment PDs should appear in the PD list after they are created
=> [ch26659] Amendment PDs should appear in the PD list after they are created

src_ts/components/layout/support-btn.ts
[ch26816] Update support link in header
=> [ch26816] Update support link in header

src_ts/components/common/components/support-btn.ts
=> [ch26816] [epd branch]Update support link

src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts, src_ts/components/pages/partners/partners-module.ts
=> [ch26166][epd]Update count on activities goups change

.circleci/config.yml, src_ts/components/app-modules/partners/data/partner-item-data.ts
=> [ch26708]Show errors details instead of generic message on importing partner

package-lock.json, package.json
[ch26862] Read Only on file fields should not show Upload File. A simple - should suffice
=> [ch26862] Read Only on file fields should not show Upload File. A simple - should suffice

polymer.json
=> [ch26887] Map icons missing

src_ts/components/app-modules/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts
=> [ch26657] Add reference link to monitoring activities in Partner Assurance Tab

src_ts/components/common/common-data.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts
https://github.com/unicef/intervention-tab-pages/pull/514
=> [ch26761] Add provided by to common data

src_ts/components/pages/interventions/pages/new/intervention-new.ts
=> [ch27034]Issue with front end validation not preventing the request to be sent to backend

src_ts/components/pages/interventions/data/interventions-list-data.ts
=> [ch27062]Fix filtering

src_ts/components/common/mixins/lists-common-mixin.ts, src_ts/components/pages/interventions/data/interventions-list-data.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts
=> [ch23152] Sent to partner filter

src_ts/components/pages/settings/components/disaggregation-list.ts
[ch27154] Update Disaggregations associated with a PD: Toggle incorrect behavior
=> [ch27154] Update Disaggregations associated with a PD: Toggle incorrect behavior

src_ts/components/app-modules/interventions/mixins/modified-intervention-fields-mixin.ts
=> [ch27384]Don't send reference_number_year for SSFA

package-lock.json, package.json
=> [ch26841]Lit etools-info-tooltip

src_ts/components/app-modules/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts
=> [ch26818] Prevent loading activities if partnerId is not defined

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/ro.json, src_ts/components/pages/interventions/data/interventions-list-data.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts
=> [ch23152]Editable by filter

package-lock.json, package.json
=> [ch27521]etools-table update

src_ts/components/pages/partners/pages/details/partner-details.ts
[ch27473] Inconsistent behavior on Partner Details - HACT Risk Rating label
=> [ch27473] Inconsistent behavior on Partner Details - HACT Risk Rating label

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/components/app-shell/header/page-header.ts
[ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol
=> [ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol

src_ts/components/pages/partners/components/new-partner-dialog.ts, src_ts/components/pages/partners/pages/details/components/add-edit-staff-members.ts, src_ts/components/pages/partners/pages/details/components/edit-core-values-assessment.ts, src_ts/components/pages/partners/pages/financial-assurance/components/assessment-dialog.ts, src_ts/components/pages/partners/pages/financial-assurance/components/hact-edit-dialog.ts
[ch27733] Partner pages - migrate dialogs to LitElement
=> [ch27733] Partner pages - migrate dialogs to LitElement

.eslintrc.json, package-lock.json, package.json, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common/components/monitoring-visits-list.ts, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/not-found/not-found.ts, src_ts/components/pages/partners/components/new-partner-dialog.ts, src_ts/components/pages/partners/pages/details/partner-details.ts, src_ts/components/pages/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/partners/pages/list/partners-list.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/pages/reports/components/reports-display-list.ts, src_ts/components/pages/reports/reports-module.ts
=> [ch27264]Upgrade linting tools

src_ts/components/common/mixins/common-mixin-lit.ts, src_ts/components/common/mixins/module-common-mixin-lit.ts, src_ts/components/common/mixins/module-routing-mixin-lit.ts, src_ts/components/common/mixins/scroll-control-mixin-lit.ts, src_ts/components/pages/partners/data/partner-item-data.ts, src_ts/components/pages/partners/mixins/staff-members-data-mixin.ts, src_ts/components/pages/partners/pages/details/components/edit-core-values-assessment.ts, src_ts/components/pages/partners/pages/details/components/staff-members.ts, src_ts/components/pages/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.styles.ts, src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/styles/buttons-styles-lit.ts, src_ts/components/styles/page-content-header-slotted-styles-lit.ts, src_ts/components/styles/page-layout-styles-lit.ts
[ch27920] Partner Details - Assurance - Programmatic Visits,Monitoring Activities, Other Assessments
=> [ch27920] Partner Details - Assurance - Programmatic Visits,Monitoring Activities, Other Assessments

src_ts/components/common/mixins/lists-common-mixin.ts, src_ts/components/pages/partners/components/partner-status.ts, src_ts/components/pages/reports/components/reports-display-list.ts
=> [ch27996]Component migration fixes

src_ts/components/common/mixins/lists-common-mixin.ts, src_ts/components/pages/partners/components/partner-status.ts, src_ts/components/pages/reports/components/reports-display-list.ts
=> [ch27996]Reusable components migrations fixes - migrate-to-lit branch

package-lock.json, package.json, src_ts/components/pages/partners/pages/overview/partner-overview.ts
=> [ch28038]Fix PD link on overview tab

package-lock.json, package.json, src_ts/components/common/mixins/module-common-mixin-lit.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/partners/pages/overview/partner-overview.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/utils/router.ts
=> [ch28025]Fix loading msg not shown

package-lock.json, package.json, src_ts/components/common/mixins/module-common-mixin-lit.ts, src_ts/components/pages/partners/pages/details/components/edit-core-values-assessment.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/partners/pages/overview/partner-overview.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/utils/router.ts
=> [ch28025]Fix CVA upload

package-lock.json, package.json
[ch28050] Fund reservation related tooltip showing up when there is no Fund reservation
=> [ch28050] Fund reservation related tooltip showing up when there is no Fund reservation

src_ts/components/common/mixins/module-common-mixin-lit.ts, src_ts/components/pages/partners/partners-module.ts
[ch28025]Preserve filters on page refresh
=> [ch28025]Preserve filters on page refresh

src_ts/components/pages/partners/pages/financial-assurance/components/assessments-items.ts
[ch28244] Partners Assurance: Saved Other Assessments displayed only at refresh
=> [ch28244] Partners Assurance: Saved Other Assessments displayed only at refresh

src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts
[ch28234] Partners Assurance tab: Monitoring Activities ongoing Loading data
=> [ch28234] Partners Assurance tab: Monitoring Activities ongoing Loading data

src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.styles.ts, src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts
[ch28234] Monitoring Activities: fix Loading data, style issues, drag&drop
=> [ch28234] Monitoring Activities: fix Loading data, style issues, drag&drop

src_ts/components/pages/partners/pages/overview/partner-overview.ts
[ch28254] Inconsistency on Partner Cash details from list and Partner Cash details from Partners-Overview
=> [ch28254] Inconsistency on Partner Cash details from list and Partner Cash details from Partners-Overview

src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/partners/pages/overview/partner-overview.ts
[ch28248] Consider adding Pagination on Partner - Overview tab - Partner Overview
=> [ch28248] Consider adding Pagination on Partner - Overview tab - Partner Overview

src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/partners/pages/list/governments-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/components/pages/partners/pages/list/partners-list.ts
=> [ch28428]Governments - default filter not selected after certain navigation

src_ts/components/common/user/user-data-mixin.ts
=> [ch27536]Redirect to epd based on user

.circleci/config.yml, src_ts/components/app-modules/reports/pages/progress/components/indicator-details.ts
=> [ch28760]Location title to name

.circleci/config.yml, src_ts/components/app-modules/reports/pages/progress/components/indicator-details.ts
* [ch28760]Location title to name (#1820)
Co-authored-by: Adriana Trif <trif.corina.adriana@gmail.com>
=> Staging (location name hotfix)

src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/data/agreement-item-data.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch28740] Agreements details - not redirected after creation of a new agreement
=> [ch28740] Agreements details - not redirected after creation of a new agreement

src_ts/components/pages/interventions/pages/list/interventions-list.ts
[ch28742] PD List style issue - Status and Title content collide
=> [ch28742] PD List style issue - Status and Title content collide

src_ts/components/pages/reports/pages/summary/report-summary.ts
[ch28655] PRP: Remove FACE form attachment field from PRP and PMP
=> [ch28655] PRP: Remove FACE form attachment field from PRP and PMP

package-lock.json, package.json, src_ts/components/app-modules/agreements/agreements-module.ts, src_ts/components/app-modules/interventions/interventions-module.ts, src_ts/components/app-modules/partners/partners-module.ts, src_ts/components/app-modules/reports/reports-module.ts, src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts
=> [ch17503]Matomo tracking additions

package-lock.json, package.json, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/components/pages/reports/pages/list/reports-list.ts
[ch29012] Update etools-filters in apps
=> [ch29012] Update etools-filters in apps

src_ts/components/common/mixins/module-routing-mixin-lit.ts, src_ts/components/common/mixins/module-routing-mixin.ts, src_ts/components/pages/interventions/interventions-module.ts
=> [ch28795] Add route to workplan-edit

src_ts/components/pages/reports/pages/list/reports-list.ts
[ch29220] Reports: Page not found when accessing the PD ref
=> [ch29220] Reports: Page not found when accessing the PD ref

src_ts/components/pages/partners/pages/overview/partner-overview.ts
[ch29204] Console error on Partners/Agreements
=> [ch29204] Console error on Partners/Agreements

src_ts/components/pages/reports/pages/list/reports-list.ts
[ch29217] Reports: Misplaced tooltip on list
=> [ch29217] Reports: Misplaced tooltip on list

src_ts/components/app-shell/menu/app-menu.ts
=> [ch29414]Update Implementation Intelligence link

src_ts/components/app-shell/menu/app-menu.ts
=> [ch29414]Imple. Intell. link

package-lock.json, package.json
=> [ch29607]Update etools-modules-common

src_ts/components/common/components/etools-ram-indicators.ts, src_ts/components/pages/reports/pages/progress/report-progress.ts
[ch29667] Cannot access Reports details
=> [ch29667] Cannot access Reports details

src_ts/components/app-shell/menu/mixins/app-menu-mixin.ts, src_ts/components/pages/settings/components/add-disaggregation-dialog.ts
=> [ch29686]Fix - at least 2 disaggregations required

src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
=> [ch29676]Increase field width for Activation Protocol

package-lock.json, package.json
=> [ch29745]Update etools-currency-amount-input

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch29782] Agreement Type empty for legacy SSFAs
=> [ch29782] Agreement Type empty for legacy SSFAs

src_ts/components/pages/interventions/pages/list/interventions-filters.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts
[ch29825] PD list ordering and default filters changes
=> [ch29825] PD list ordering and default filters changes

polymer.json
=> [ch29824] Add all icons to build

src_ts/components/pages/reports/reports-module.ts
[ch29793] Reports: 404 when clicking the PD ref
=> [ch29793] Reports: 404 when clicking the PD ref

src_ts/components/app-shell/app-theme.ts, src_ts/components/pages/reports/reports-module.ts
[ch29822] Save btn focus is not enough to be just bold. needs better signifier
=> [ch29822] Save btn focus is not enough to be just bold. needs better signifier

Dockerfile
=> [ch29815]Fix app not working on Firefox

index.html, polymer.json, src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/reports/reports-module.ts
[ch29784] CP Structure field should not have underline in readonly mode
=> [ch29784] CP Structure field should not have underline in readonly mode

.circleci/config.yml, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts
=> [ch29750]Agreement fixes

.circleci/config.yml, src_ts/components/common/mixins/lists-common-mixin-lit.ts, src_ts/components/common/mixins/lists-common-mixin.ts, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/utils/navigation-helper.ts, src_ts/components/utils/routes.ts
=> [ch29787][ch29928]Fixes for Save agreement amendments & routing tweaks

src_ts/components/pages/agreements/data/agreements-list-data.ts, src_ts/components/pages/interventions/data/interventions-list-data.ts, src_ts/components/pages/partners/data/partners-list-data.ts
=> [ch29931] Reload page on 'db closed' error

src_ts/components/pages/reports/pages/list/reports-list.ts
=> [ch29795] Fix tooltip position

src_ts/components/common/components/etools-ram-indicators.ts
=> [ch30027] Reset indicators data on input properties change

src_ts/components/pages/reports/pages/list/reports-list.ts
=> [ch30016] Fix page size change on reports page

cors-anywhere/index.js, package-lock.json, package.json, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/pages/reports/pages/progress/components/indicator-details.ts, src_ts/components/pages/reports/reports-module.ts, src_ts/config/config.ts
[ch30024] Reports migration issues
=> [ch30024] Reports migration issues

src_ts/components/pages/reports/pages/list/reports-list.ts, src_ts/components/pages/reports/reports-module.ts
=> [ch30030]Fix error on Accept Report

src_ts/components/pages/reports/pages/list/reports-list.ts, src_ts/config/config.ts
=> [ch30074]Add space between names

.circleci/config.yml, src_ts/components/pages/reports/pages/list/reports-list.ts, src_ts/config/config.ts
=> [ch30039]Fix intermittent empty Reports list

src_ts/components/common/mixins/list-data-mixin-lit.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts
=> [ch29929]Fix partners, agreements duplicate requests

src_ts/components/app-shell/header/page-header.ts
=> [ch30144]Fix language change

src_ts/components/app-shell/header/data-refresh-dialog.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/redux/reducers/agreements.ts
=> [ch29928]Fix refresh All data while on agreements page

src_ts/components/pages/reports/pages/summary/sent-bk-comments.ts
=> [ch30104] Style issues

src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
[ch30150] Add new PD: Transparent tooltips
=> [ch30150] Add new PD: Transparent tooltips

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch30006] MOU Agreement End Date- Disable days before Start Date
=> [ch30006] MOU Agreement End Date- Disable days before Start Date

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch30175] Agreement details -Label cut off despite available space
=> [ch30175] Agreement details -Label cut off despite available space

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch30211] MOU agreement - labels cut off
=> [ch30211] MOU agreement - labels cut off

src_ts/components/pages/agreements/data/agreements-list-data.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts
=> [ch30212]Fix agreements list missing Special Cond Pcas

src_ts/components/pages/agreements/data/agreements-list-data.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts
=> [ch30206]Fix export filters by psea dates

src_ts/components/pages/agreements/data/agreements-list-data.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/components/pages/reports/pages/list/reports-list.ts
=> [ch30214]Reports - increase tooltip text

src_ts/app-shell.ts, src_ts/components/pages/agreements/data/agreements-list-data.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts
=> [ch30008]Replace substr

src_ts/components/pages/agreements/pages/details/agreement-details.ts
=> [ch30285]Fix empty agreement fields on first access

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch30218] Agreement details - Generate btn should not have underline
=> [ch30218] Agreement details - Generate btn should not have underline

src_ts/components/pages/agreements/pages/list/agreements-list.ts
[ch30301] List loses records after multiple sorts
=> [ch30301] List loses records after multiple sorts

src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/reports/reports-module.ts
[ch30304] Export dropdown options can not be reached with keyboard navigation
=> [ch30304] Export dropdown options can not be reached with keyboard navigation

src_ts/components/pages/interventions/pages/list/interventions-list.ts
[ch30031] FR warnings not displayed on PD list
=> [ch30031] FR warnings not displayed on PD list

src_ts/components/pages/reports/pages/progress/components/indicator-details.ts
=> [ch30342]Reports-remove UNICEF tab

src_ts/app-shell.ts, src_ts/components/utils/routes.ts, src_ts/redux/actions/app.ts
=> [ch29659] Add global reset action

src_ts/app-shell.ts, src_ts/components/utils/routes.ts
=> [ch29659]Fix progress tab not loading

package-lock.json, package.json
[ch30333] FR misplaced warnings
=> [ch30333] FR misplaced warnings

src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch30258] Add Agreement:  details removed when Errors at saving agreement are present #2
=> [ch30258] Add Agreement:  details removed when Errors at saving agreement are present #2

src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
=> [ch30422]Error msg for Doc Title field

src_ts/components/common/mixins/utils-mixin.ts
[ch30357] PD Reports: display total cumulative progress and achievement in reporting period with decimals
=> [ch30357] PD Reports: display total cumulative progress and achievement in reporting period with decimals

src_ts/components/pages/reports/reports-module.ts
[ch30409] Report details: Export dropdown options can not be reached with keyboard navigation
=> [ch30409] Report details: Export dropdown options can not be reached with keyboard navigation

package-lock.json, package.json
[ch30416] Refactor how min date is set for datepicker in edit-hru-dialog.ts file
=> [ch30416] Refactor how min date is set for datepicker in edit-hru-dialog.ts file

src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/reports/pages/list/reports-list.ts
=> [ch30215]Reports - Reduce list loading on nav

src_ts/components/common/mixins/utils-mixin.ts, src_ts/components/pages/reports/pages/progress/report-progress.ts
[ch30517] Icon used for Ratio Indicators is the one for Percentage Indicators [PD/SSFA > Reports / Reports]
=> [ch30517] Icon used for Ratio Indicators is the one for Percentage Indicators [PD/SSFA > Reports / Reports]

src_ts/components/common/components/monitoring-visits-list.ts, src_ts/components/pages/partners/pages/financial-assurance/components/partner-monitoring-visits-list.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts
[ch30472] monitoring-visits-list migration to LitELement
=> [ch30472] monitoring-visits-list migration to LitELement

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch30197] Add Agreement: [Intermittent] Agreement type validation error incorrectly displayed
=> [ch30197] Add Agreement: [Intermittent] Agreement type validation error incorrectly displayed

.circleci/config.yml, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch29990] Refactoring on Agreements related code
=> [ch29990] Refactoring on Agreements related code

src_ts/components/pages/partners/pages/details/components/staff-members.ts, src_ts/components/pages/partners/pages/details/partner-details.ts, src_ts/components/pages/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/pages/reports/pages/summary/report-summary.ts, src_ts/components/pages/reports/reports-module.ts
=> [ch30668]Fix reopen dialog after cancelling edit

src_ts/components/pages/reports/pages/list/reports-filters.ts, src_ts/components/pages/reports/pages/list/reports-list.ts
=> [ch28550]Year filter for Reports

src_ts/components/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.ts
=> [ch30858]Ensure target,baseline are numbers(develop branch)

src_ts/components/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.ts, src_ts/components/app-modules/reports/pages/list/reports-list.ts, src_ts/components/app-modules/reports/reports-module.ts
=> [ch28550]Year filter for Reports (develop branch)

src_ts/components/app-shell/header/page-header.ts
=> [ch30100]Set language from user.preferences.language

src_ts/components/app-modules/reports/pages/list/reports-list.ts, src_ts/components/app-modules/reports/reports-module.ts
Reverts unicef/etools-partnership-management#1963
=> Revert "[ch28550]Year filter for Reports (develop branch)"

src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/page-header.ts
[ch31321] Improve the language dropdown
=> [ch31321] Improve the language dropdown

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/pt.json, assets/i18n/ro.json, assets/i18n/ru.json, src_ts/components/endpoints/endpoints.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts, src_ts/components/pages/interventions/pages/new/ecn-number-dialog.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
=> [ch31411]Import eCN

src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts
[ch31704] Import eCN, add filtering by Partner
=> [ch31704] Import eCN, add filtering by Partner

.circleci/config.yml, src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts
=> [ch31749]After eCN import, stay on details page

.circleci/config.yml, package-lock.json, package.json, src_ts/components/common/mixins/list-data-mixin-lit.ts, src_ts/components/endpoints/endpoints.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts
=> [ch31751]Import eCN: Record not found on the list after the import

src_ts/components/pages/interventions/pages/new/intervention-new.ts
=> [ch31748]Redirect to list on cancel new PD

package-lock.json, package.json
=> [ch31858]Update etools-modules-common

src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts
[ch31944] Import ECN fix  dropdown layout
=> [ch31944] Import ECN fix  dropdown layout

src_ts/app-shell.ts
=> [ch31232]App-shell/ remove dom-if

src_ts/app-shell.ts, src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/utils/router.ts
=> [ch31232]Partners module -remove app-route

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ro.json, assets/i18n/ru.json
[ch31395] Missing translations
=> [ch31395] Missing translations

src_ts/app-shell.ts
[ch32164] Navigation/Leave the page incorrect behavior
=> [ch32164] Navigation/Leave the page incorrect behavior

src_ts/components/pages/reports/pages/list/reports-list.ts
[ch32192] Intermittent: No options available in dropdown lists after page refresh
=> [ch32192] Intermittent: No options available in dropdown lists after page refresh

src_ts/components/common/common-data.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts
=> [ch32192]Intermittent: No options available in dropdown lists after page refresh

tsconfig.json
=> [ch32342]Fix spanish translations not working

src_ts/components/common/common-data.ts, src_ts/components/pages/agreements/data/agreements-list-data.ts, src_ts/components/pages/interventions/data/intervention-item-data.ts, src_ts/components/pages/interventions/data/interventions-list-data.ts, src_ts/components/pages/partners/data/partners-list-data.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts
=> [ch32321]Some newly created records not displayed in the list

src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts
=> [ch29386]Partner fin assurance - Fix FAM Report link

src_ts/app-shell.ts
=> [ch32406]Fix Page scrolls up after upload file

src_ts/components/pages/reports/pages/summary/report-summary.ts
[ch31397] Missing Russian translations part V (Reports & Settings) - Other Label
=> [ch31397] Missing Russian translations part V (Reports & Settings) - Other Label

package-lock.json, package.json
[ch32471] Upload button translation at language change updates after refresh
=> [ch32471] Upload button translation at language change updates after refresh

.circleci/config.yml, src_ts/redux/actions/app.ts
=> [ch32460] Set comment mode timing

src_ts/app-shell.ts, src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/common/mixins/uploads-mixin.ts
[ch32461] App blocked in country data changing
=> [ch32461] App blocked in country data changing

src_ts/components/pages/interventions/pages/list/interventions-list.ts
[ch32490] Navigation console error
=> [ch32490] Navigation console error

src_ts/components/app-shell/header/page-header.ts, src_ts/config/app-constants.ts
=> [ch32445]Fix Ro langnuage on page refresh

src_ts/components/app-shell/header/page-header.ts
=> [ch32494]Fix difference between av. apps in menu app and app-selector

src_ts/components/app-shell/header/countries-dropdown.ts
[ch32539] Country change no longer working
=> [ch32539] Country change no longer working

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/components/app-shell/header/data-refresh-dialog.ts, src_ts/components/common/components/etools-ram-indicators.ts, src_ts/components/common/mixins/ajax-server-errors-mixin-lit.ts, src_ts/components/common/mixins/repeatable-data-sets-mixin.ts, src_ts/components/common/mixins/staff-members-data-mixin-lit.ts, src_ts/components/common/user/profile-operations-mixin.ts, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/data/agreement-item-data.ts, src_ts/components/pages/agreements/pages/details/components/generate-PCA-dialog.ts, src_ts/components/pages/interventions/data/intervention-item-data.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/data/partner-item-data.ts, src_ts/components/pages/partners/pages/details/partner-details.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/pages/reports/reports-module.ts
=> [ch32526]All toasts to have ok btn

src_ts/app-shell.ts
[ch32581] Error on redirect to page not found
=> [ch32581] Error on redirect to page not found

package-lock.json, package.json, src_ts/components/pages/agreements/data/agreement-item-data.ts
[ch32643] Agreements list not updated after item is deleted
[ch32646] App selector redirects to not-found before opening the selected app
=> [ch32643] Agreements list not updated after item is deleted, [ch32646] App selector redirects to not-found before opening the selected app

src_ts/components/common/components/etools-error-messages-box.ts
[ch32641] Flash of previous error message
=> [ch32641] Flash of previous error message

package-lock.json, package.json
[ch32652] Filters dropdown: scroll not working, you can only drag the bar
=> [ch32652] Filters dropdown: scroll not working, you can only drag the bar

src_ts/components/pages/interventions/pages/new/intervention-new.ts
[ch32690] Display users as inactive if they are marked as inactive
=> [ch32690] Display users as inactive if they are marked as inactive

package-lock.json, package.json
[ch32712] Cannot close tooltips
=> [ch32712] Cannot close tooltips

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch32654] Click on "Cancel Partner Authorized Officers Amendment" should reset field to initial value
=> [ch32654] Click on "Cancel Partner Authorized Officers Amendment" should reset field to initial value

package-lock.json, package.json
[ch32762] Tab navigation not working properly
=> [ch32762] Tab navigation not working properly

package-lock.json, package.json
[ch32725] Tab navigation on dropdowns not working properly
=> [ch32725] Tab navigation on dropdowns not working properly

src_ts/components/common/components/etools-cp-structure.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch32666] Agreements: Changing CP structure on a draft should also update CP End Date visually for reference
=> [ch32666] Agreements: Changing CP structure on a draft should also update CP End Date visually for reference

src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/typings/partner.types.ts
Reverts unicef/etools-partnership-management#2072
=> Revert "[ch32663]Partner Organization on PD should only show partners which have agreements"

index.html
[ch32850] Prevent Help icon to cover dialog
=> [ch32850] Prevent Help icon to cover dialog

src_ts/components/pages/agreements/pages/details/components/generate-PCA-dialog.ts
[ch32967] Comment out from the dropdown all other PCA Templates except for the updated English one.
=> [ch32967] Comment out from the dropdown all other PCA Templates except for the updated English one.

src_ts/components/pages/interventions/interventions-module.ts
[ch32484] Update toasts related to Headquarters Contribution
=> [ch32484] Update toasts related to Headquarters Contribution

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json, src_ts/app-shell.ts, src_ts/components/common/common-data.ts, src_ts/components/endpoints/endpoints.ts
[ch33014] Translations: Values not updated at language switch
=> [ch33014] Translations: Values not updated at language switch

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json, src_ts/components/common/common-data.ts, src_ts/components/common/mixins/lists-common-mixin-lit.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/pages/reports/pages/list/reports-list.ts, src_ts/components/utils/utils.ts, src_ts/redux/reducers/common-data.ts
[ch33064] Translations: Values not updated at language switch part II
=> [ch33064] Translations: Values not updated at language switch part II

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json
[ch33087] ePD, PMP, update Translations (update and use Localazy)
=> [ch33087] ePD, PMP, update Translations (update and use Localazy)

package-lock.json, package.json
[ch32793] Tab navigation: 13 tabs to skip the App selector and reach the Language dropdown
=> [ch32793] Tab navigation: 13 tabs to skip the App selector and reach the Language dropdown

package-lock.json, package.json
=> [ch33096]Issue in multi-dropdown, when clicking on the red x to unselect an item

src_ts/components/pages/interventions/pages/new/intervention-new.styles.ts
=> [ch33143]In Arabic lang, the Add PD form has style issues

package-lock.json, package.json
=> [ch33128]In Arabic lang, app-selector(waffle menu) is cutt off when opened

.circleci/config.yml, polymer.json
[ch33127] Translations: Console error at language switch
=> [ch33127] Translations: Console error at language switch

src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/partners/pages/overview/partner-overview.ts, src_ts/components/styles/risk-rating-styles-lit.ts
[ch33189] Style issues - misalignment & label cut off
=> [ch33189] Style issues - misalignment & label cut off

src_ts/components/common/components/etools-status/etools-status-styles.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/styles/page-layout-styles-lit.ts
[ch33152] In Arabic lang - Style issues on Partner Assurance page
=> [ch33152] In Arabic lang - Style issues on Partner Assurance page

package-lock.json, package.json
=> [ch33170]Update e-ajax for bk err translate

src_ts/components/app-shell/header/countries-dropdown.ts
=> [ch33192][Intermittent] Partners list empty on country change

src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/partners/partners-module.ts
=> [ch33186]Fix redirect to page not found

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/utils/navigation-helper.ts
=> [ch33185]Routing clean up

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/utils/navigation-helper.ts
[ch33185] Page remains in loading state when accessing '.../pmp/agreements'
=> [ch33185] Page remains in loading state when accessing '.../pmp/agreements'

src_ts/app-shell.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/mixins/app-menu-mixin.ts, src_ts/redux/actions/app.ts, src_ts/redux/reducers/app.ts
[ch33266]
TODO - on squash merge connect to https://github.com/unicef/intervention-tab-pages/pull/945
=> [ch33266]Remove Side-menu state from redux store

src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts
=> [ch33274]Arabic: Missing translations FE

src_ts/components/app-shell/header/page-header.ts
(Hotfix) Hide header text if application is on production
=> (Hotfix) Hide header text if application is on production

package-lock.json, package.json
[ch33265] Arabic: tooltip overlaps the upload button for the Supply items list
=> [ch33265] Arabic: tooltip overlaps the upload button for the Supply items list

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json, index.html, src_ts/components/app-shell/header/page-header.ts, src_ts/components/common/components/support-btn.ts
=> [ch33334][Hotfix]Remove Zendesk, add Support btn in page header

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json, index.html, package-lock.json, src_ts/components/app-shell/header/page-header.ts, src_ts/components/common/components/support-btn.ts
=> [ch33334][after-code-freeze]Remove Zendesk, add Support btn in page header

package-lock.json, package.json
[ch33296] Multi select dropdown Search input covered by app header
=> [ch33296] Multi select dropdown Search input covered by app header

package-lock.json, package.json
=> [ch27289] Update etools-piwik - translated txt on Filters btn

package-lock.json, package.json
=> [ch33404]Fix info icon click opening dropdown also

src_ts/components/pages/agreements/pages/details/agreement-details.ts
[ch33478] Misalignements - agreement details, review tab, amendments
=> [ch33478] Misalignements - agreement details, review tab, amendments

src_ts/components/common/components/etools-status/etools-status-common-mixin-lit.ts, src_ts/components/pages/agreements/pages/components/agreement-status.ts, src_ts/components/pages/partners/components/partner-status.ts
=> [ch33464]Translations on confirmation dialog for delete agreement, partner, special report (refactor)

package-lock.json, package.json, src_ts/components/common/components/etools-status/etools-action-button.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/reports/reports-module.ts
[ch33131] [ch33272] [ch33140] Fixes
=> [ch33131] [ch33272] [ch33140] Fixes

src_ts/components/pages/interventions/pages/list/interventions-list.ts
[ch33482] Redirected to PD list after click on Add New PD/SPD
=> [ch33482] Redirected to PD list after click on Add New PD/SPD

src_ts/components/pages/interventions/pages/list/interventions-list.ts
Reverts unicef/etools-partnership-management#2143
=> Revert "[ch33482] Redirected to PD list after click on Add New PD/SPD"

src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/interventions/pages/new/ecn-import-dialog.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
[ch33474] After amendment merge, the [Amended] PD remains in the PD list and gives a 404/not found when it's accessed
=> [ch33474] After amendment merge, the [Amended] PD remains in the PD list and gives a 404/not found when it's accessed

assets/i18n/fr.json
[ch33236] French translations: Adjust Filters labels with the values returned
=> [ch33236] French translations: Adjust Filters labels with the values returned

.circleci/config.yml, src_ts/components/pages/agreements/pages/details/agreement-details.ts
=> [ch33173]Details not displayed on Draft Saved Agreements -staging

src_ts/components/pages/agreements/pages/details/agreement-details.ts
=> [ch33173]Details not displayed on Draft Saved Agreements - dev

src_ts/components/common/common-data.ts
[ch33638] Geographical Coverage: The Partner does not see the group location options
=> [ch33638] Geographical Coverage: The Partner does not see the group location options

src_ts/components/pages/reports/pages/summary/report-summary.ts
[ch33775] Incorrect Report status
=> [ch33775] Incorrect Report status

package-lock.json, package.json
[ch33834] Sites for Programmatic Visits - only sites selected on the PD to be available
=> [ch33834] Sites for Programmatic Visits - only sites selected on the PD to be available

src_ts/components/common/mixins/staff-members-data-mixin-lit.ts, src_ts/models/partners.models.ts
=> [ch33894]Prefix Inactive staff members on agreement details

src_ts/components/common/mixins/staff-members-data-mixin-lit.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/pages/details/components/staff-members.ts, src_ts/models/partners.models.ts, src_ts/typings/partner.types.ts
=> [ch33888]Prefix inoperative partner staff members

src_ts/components/endpoints/endpoints.ts
[ch33921] Replace `v2/partners` endpoints with `pmp/v3/partners`
=> [ch33921] Replace `v2/partners` endpoints with `pmp/v3/partners`

package-lock.json, package.json
=> [ch33950]Update etools-ajax

src_ts/app-shell.ts, src_ts/components/common/common-data.ts, src_ts/components/common/user/user-data-mixin.ts
[ch33958] No options available for dropdown list options after a page reload
=> [ch33958]Keep Loading overlay active until common data is loaded

src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts
=> [ch33482]Fix intermittent redir to list when accessing add pd page

src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/pages/details/components/staff-members.ts, src_ts/models/partners.models.ts
=> [ch34085]Replace Inoperative with No Access

src_ts/components/app-shell/app-theme.ts
[ch33917] Comments panel: On expand/collapse the comments panel header has corners
=> [ch33917] Comments panel: On expand/collapse the comments panel header has corners

index.html, package-lock.json, package.json, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/components/pages/partners/pages/overview/partner-overview.ts
=> [ch34640]Spacing/alignement fixes

index.html, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
=> [ch34643]Shoelace - validation msg doesnt show up sometimes

index.html, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts
=> [ch34632]Shoelace dropdown - darker text color, font family

package-lock.json, package.json
Adding etools-modules-common updated with etools-unicef
=> Adding etools-modules-common updated with etools-unicef

src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/pages/details/components/edit-core-values-assessment.ts, src_ts/components/pages/partners/pages/details/partner-details.ts, src_ts/components/pages/reports/pages/progress/components/report-overall.ts, src_ts/components/pages/reports/pages/progress/components/sr-details.ts, src_ts/components/pages/reports/pages/summary/report-summary.ts, src_ts/components/pages/reports/pages/summary/sent-bk-comments.ts
=> [ch34734]Replace etools-form-element-wrapper

src_ts/components/common/mixins/missing-dropdown-options-mixin.ts, src_ts/components/common/mixins/repeatable-data-sets-mixin.ts
=> Lint issues

src_ts/components/common/components/etools-form-element-wrapper.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/components/partner-status.ts
=> [ch34777]Fix pd create

package-lock.json, package.json, src_ts/components/common/mixins/list-filters-mixin-lit.ts, src_ts/components/pages/agreements/data/agreement-termination.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/agreements/pages/details/components/amendments/add-ag-amendment-dialog.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/interventions/pages/new/intervention-new.ts, src_ts/components/pages/partners/pages/financial-assurance/components/assessment-dialog.ts
=> Adding etools-date-time migration

package-lock.json, package.json, src_ts/components/pages/reports/pages/list/reports-list.ts, src_ts/components/pages/reports/pages/progress/report-progress.ts, src_ts/components/pages/reports/reports-module.ts, src_ts/redux/actions/app.ts
=> [ch34784]Fix other info tab

src_ts/components/pages/partners/partners-module.ts
[ch34913] On language change tab bottom border not adjusting according to text
=> [ch34913] On language change tab bottom border not adjusting according to text

src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts
=> [ch34953]Sync agreement details links styles

index.html
=> [ch34946]Fix dropdown bg color when focused

src_ts/components/pages/partners/pages/details/partner-details.ts
=> [ch34977]Update date icon

package.json, src_ts/components/app-shell/header/page-header.ts, src_ts/components/common/components/etools-status/etools-action-button.ts, src_ts/components/common/components/icons-actions.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/partners/pages/details/components/staff-members.ts, src_ts/components/pages/partners/pages/details/partner-details.ts, src_ts/components/pages/partners/pages/financial-assurance/components/assessments-items.ts, src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/reports/pages/progress/report-progress.ts, src_ts/components/pages/reports/reports-module.ts, src_ts/components/pages/settings/components/add-disaggregation-dialog.ts, src_ts/components/pages/settings/components/disaggregation-list.ts, src_ts/components/styles/action-icon-btns-styles.ts
=> [ch35000]Replace paper-icon-button with sl-icon-button

src_ts/components/pages/partners/partners-module.ts
[ch35074] Remove PMP Partners Export button, ePD list Export button
=> [ch35074] Remove PMP Partners Export button, ePD list Export button

package.json, src_ts/app-shell.ts, src_ts/components/app-shell/header/data-refresh-dialog.ts, src_ts/components/common/components/etools-ram-indicators.ts, src_ts/components/pages/reports/pages/progress/components/sr-details.ts, src_ts/components/pages/reports/pages/progress/report-progress.ts, src_ts/components/pages/reports/pages/summary/report-summary.ts
=> [ch35097]Replace iron-label

src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/pages/partners/pages/details/components/staff-members.ts, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts, src_ts/components/pages/reports/components/report-status.ts
=> Fix icons names

package-lock.json, package.json, src_ts/app-shell.ts
[ch35138] Move etools-toasts to etools-unicef
=> [ch35138] Move etools-toasts to etools-unicef

src_ts/app-shell.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts, src_ts/components/pages/agreements/pages/list/agreements-list.ts, src_ts/components/pages/interventions/pages/list/interventions-list.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts, src_ts/components/pages/partners/pages/list/partners-list-base.ts, src_ts/components/pages/reports/pages/list/reports-list.ts
[ch35175] Replace iron selector
=> [ch35175] Replace iron selector

package-lock.json, package.json
=> Fix icons path

src_ts/components/common/components/icons-actions.ts
[ch35281] PMP - Core Values Assessments buttons issue
=> [ch35281] PMP - Core Values Assessments buttons issue

assets/css/app-theme.css, package-lock.json, package.json, src_ts/components/common/components/etools-error-messages-box.ts, src_ts/components/common/components/etools-status/etools-action-button.ts, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/components/pages/agreements/pages/details/components/amendments/agreement-amendments.ts, src_ts/components/pages/interventions/interventions-module.ts, src_ts/components/pages/interventions/pages/new/intervention-new.template.ts, src_ts/components/pages/partners/pages/financial-assurance/components/hact-edit-dialog.ts, src_ts/components/pages/partners/pages/financial-assurance/components/monitoring-activities/monitoring-activities.ts, src_ts/components/pages/partners/partners-module.ts, src_ts/components/pages/reports/reports-module.ts, src_ts/components/pages/settings/components/add-disaggregation-dialog.ts
[ch35333] Clean-up, refactor, fix buttons
=> [ch35333] Clean-up, refactor, fix buttons

index.html, rollup-dev.config.js, workbox-config.js
=> Rollup fixes

package-lock.json, package.json, src_ts/components/common/components/etools-status/etools-action-button.ts, src_ts/components/pages/agreements/data/agreement-termination.ts, src_ts/components/pages/partners/components/partner-status.ts, src_ts/components/pages/reports/pages/summary/sent-bk-comments.ts
[ch35460] PMP & ePD shoelace migration issues 6, action buttons fixes
=> [ch35460] PMP & ePD shoelace migration issues 6, action buttons fixes

src_ts/components/pages/partners/partners-module.ts, src_ts/components/pages/reports/pages/progress/components/indicator-details.ts, src_ts/components/pages/settings/components/disaggregation-list.ts
[ch35612] PMP & ePD shoelace migration issues 8
=> [ch35612] PMP & ePD shoelace migration issues 8

src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/header-dropdown-styles.ts, src_ts/components/app-shell/header/organizations-dropdown.ts, src_ts/components/app-shell/header/page-header.ts
=> Header adjustments

src_ts/components/app-shell/header/organizations-dropdown.ts, src_ts/components/pages/interventions/data/intervention-item-data.ts, src_ts/components/pages/interventions/data/interventions-list-data.ts
Fixed Dexie interventions count
=> Fixed Dexie interventions count

src_ts/components/pages/partners/components/partner-status.ts
Cannot read properties of undefined (reading 'hidden') partner-status.ts:90:50
=> Cannot read properties of undefined (reading 'hidden') partner-status.ts:90:50

src_ts/components/pages/agreements/pages/details/components/amendments/add-ag-amendment-dialog.ts, src_ts/components/pages/reports/pages/list/reports-list.ts
[ch37656] UI responsive issues
=> [ch37656] UI responsive issues 

src_ts/components/pages/reports/components/report-rating-dialog.ts
[ch37626] French version of Accepting QPR not working
=> [ch37626] French version of Accepting QPR not working

src_ts/components/pages/reports/pages/progress/components/report-overall.ts, src_ts/components/pages/reports/pages/summary/accepted-comments.ts, src_ts/components/pages/reports/pages/summary/report-summary.ts
[ch35190] Comment field for UNICEF staff for quarterly progress report and final report.
=> [ch35190] Comment field for UNICEF staff for quarterly progress report and final report.

src_ts/app-shell.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/pages/gdd-interventions/gdd-interventions-module.ts
[ch39393]  Hide gPD menu link and prevent user accessing gPD module if doesn't have rights
=> [ch39393]  Hide gPD menu link and prevent user accessing gPD module if doesn't have rights

.circleci/config.yml, package-lock.json, package.json, src_ts/components/pages/settings/components/add-disaggregation-dialog.ts
[ch39548 ]Etools-modules-common improvements
=> [ch39548 ]Etools-modules-common improvements

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json, package-lock.json, package.json, src_ts/components/pages/partners/pages/financial-assurance/partner-financial-assurance.ts
[ch39585] Add 'Pending Unsupported Amount' column to to the Assessments and Assurance table in the Partner Section in PMP
=> [ch39585] Add 'Pending Unsupported Amount' column to to the Assessments and Assurance table in the Partner Section in PMP

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/pt.json, assets/i18n/ru.json, package-lock.json, package.json, src_ts/components/endpoints/endpoints.ts, src_ts/components/pages/agreements/agreements-module.ts, src_ts/components/pages/agreements/pages/details/agreement-details.ts, src_ts/redux/actions/agreements.ts, src_ts/redux/reducers/agreements.ts, src_ts/typings/agreement.types.ts
[ch39751]  Agreements (PCA)  Signed by UNICEF Representative
=> [ch39751]  Agreements (PCA)  Signed by UNICEF Representative

.circleci/config.yml, src_ts/components/common/common-data.ts, src_ts/components/pages/gpd-interventions/pages/intervention-list/intervention-list.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts
=> [ch39943] Ezhact integration

src_ts/components/pages/reports/pages/list/report-filters.ts, src_ts/components/pages/reports/pages/list/report-list.ts
[ch258996] gPD - Implement GPD Report Template in PRP
=> [ch258996] gPD - Implement GPD Report Template in PRP

src_ts/components/pages/gpd-interventions/pages/intervention-list/intervention-list.ts, src_ts/components/pages/interventions/pages/intervention-list/intervention-list.ts
[263699] Filter not working on PMP/ePD
=> [263699] Filter not working on PMP/ePD

src_ts/components/app-shell/menu/app-menu.ts
Left a TODO to remove code related for this if everything is ok
=> [271856] Removed Government Link

src_ts/components/pages/partners/pages/details/partner-details.ts
270069 - remove core value assements visibility check
=> 270069 - remove core value assements visibility check

.circleci/config.yml
#274658 [PMP/PRP] Allow changes in the reporting periods
=> #274658 [PMP/PRP] Allow changes in the reporting periods
