unicef/etools-partnership-management

app/elements/partners-view/partners-view.html

Designed efficient and reusable sorting functions
allowing for any number of sort orderings on columns,
as well as the ability to pass in custom sorting rules
through the sortRules property.

feat(partner-list) add sorting functions

---

app/elements/agreement-data/agreement-data.html
app/elements/agreements-view/agreements-view.html
app/elements/partners-view/partners-view.html
app/elements/pmp_elements.html
app/pmp.html

Move partner and agreements data elements to pmp.html,
and pass their data down into the corresponding views.

refactor(data-elements) move data elements to pmp.html

---

pmp/app-behaviors/dropdown-behavior.html

not using this api results in behavior not working in
polyfilled browsers. Works correctly now with this fix.

fix(dropdown-behavior) use Polymer dom api

---

pmp/app-shell.html

Also made permissions in dom-ifs a one-way binding

tweak to add baseUrl to href of settings, support, etc

---

pmp/app-elements/app-selector/app-selector.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/page-header/page-header.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/app-shell.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html
styles/app-theme.html
styles/grid-layout-styles.html

Adding app selector menu. Pulling header toolbar out of each iron-page and placing in top level.

Header toolbar and app selector updates

---

pmp/app-elements/app-selector/app-selector.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/page-header/page-header.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/app-shell.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html
styles/app-theme.html
styles/grid-layout-styles.html

Partner details page for government partners

Gov partner details

---

pmp/app-behaviors/list-filters-behavior.html
pmp/app-elements/interventions/intervention-data/interventions-list-data.html
pmp/app-elements/interventions/interventions-list.html

Filters will show after page refresh if the URL contains filters. Global functionality can be used on partners/agreements/governments lists.

Interventions list filters

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/partners/partners-data/partner-item-data.html

feature(new-agreement): reset form data if any left from previous loaded agreements.

feature(new-agreement): reset form data if any left from previous agreement

---

pmp/app-behaviors/object-databind-behavior.html
pmp/app-elements/governments/government-plan-result.html

gov-details fixes for passing test

---

pmp/app-elements/common-elements/etools-single-file.html
pmp/app-elements/interventions/intervention-attachments.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-review-and-sign.html
pmp/app-elements/static-common-data/dropdowns-pmp-data.html
pmp/app-elements/static-common-data/redux-behaviors/common-static-data-redux-behavior.html
pmp/pages/page-interventions.html

bower update to get latest etools-file version

Interventions attachments functionality

---

pmp/app-behaviors/repeatable-data-sets-behavior.html
pmp/app-config/etools-app-config.html
pmp/app-elements/governments/government-details.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/government-plan-result.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/app-shell.html
pmp/pages/page-governments.html

Added delete function for deleting a government intervention result or result-activity. Also fixes the bug that didn’t allow save after erring on initial save.

feat(govt-intervention-details): Added delete result and delete result-activity functionality.

---

pmp/app-config/etools-app-config.html
pmp/app-elements/interventions/intervention-data/monitoring-visits-data.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/monitoring-visits-list.html

- removed hardcoded data for monitoring visits
- added code to retrieve the data from the API

feat(monitoring-visits): Updates to intervention overview page:

---

pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/interventions-list.html

Fixed issues with list filters not working properly

List filter fixes 

---

pmp/app-elements/common-elements/etools-single-file.html
pmp/app-elements/partners/assessments-items.html

- fixed problems with validations not working properly on single-file inputs

Assessment item fixes

---

pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html

It seems test currencies data array was still here, that's why the currency dropdown displayed those 2 test values.

Intervention planned budget currency update

---

pmp/app-elements/interventions/interventions-list.html
styles/page-layout-styles.html

Added widths to parent elements.

Fixed list overflowing horizontally

---

pmp/app-behaviors/common-general-behavior.html
pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/governments/government-plan-results.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-data/interventions-list-data.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/app-elements/partners/partners-data/partners-list-data.html
pmp/app-elements/partners/partners-list.html
pmp/app-elements/partners/staff-members.html

look at individual commits for details

Multiple Tweaks

---

pmp/app-behaviors/common-general-behavior.html

file name attachment fix

---

pmp/app-elements/partners/partner-overview.html

- fixed display of related interventions
- fixed styling issues

Partner overview updates 

---

pmp/app-elements/app-selector/app-selector.html

Icons and text both link to each page.

Icons links fix

---

pmp/app-elements/agreements/agreements-list.html

- Changed Agreement Number to Refernce Number
- added status column

Agreements list fixes 

---

pmp/app-behaviors/ajax-server-errors-behavior.html
pmp/app-behaviors/common-general-behavior.html
pmp/app-elements/agreements/partner-authorized-officers.html
pmp/app-elements/common-elements/etools-date-input.html
pmp/app-elements/common-elements/etools-error-messages-box.html
pmp/app-elements/common-elements/etools-single-file.html
pmp/app-elements/partners/assessments-items.html
pmp/app-elements/partners/partner-details.html
pmp/app-elements/partners/partner-status.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/app-elements/partners/staff-members.html
pmp/pages/page-partners.html

This PR will solve issues: 7, 22, 48, 49 and 53 from issues list.

Partner details page fixes

---

pmp/app-elements/interventions/intervention-data/interventions-list-data.html

Interventions list date filter fixes

---

pmp/app-behaviors/ajax-server-errors-behavior.html
pmp/app-behaviors/common-general-behavior.html
pmp/app-elements/agreements/agreement-amendments.html
pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/common-elements/etools-date-input.html
pmp/app-elements/partners/partner-details.html
pmp/pages/page-agreements.html
pmp/pages/page-partners.html
styles/page-layout-styles.html

Agreements issues:
* prevent empty start date according with specifications: "Change value to latest date between etools(2.2.7) and etools(2.2.9); THEN prompt user that the date has been updated"
* issue 46 - esmm update to use selected, it should populate when it has selected value and options or when the selected changes.
* issue 63 - etools-error-messages-box used for showing server errors
* issue 118 - duplicate for 63
* other small fixes, esmm dropdowns set to work with selected property, replaced paper-inputs used for dates with etools-date-field element

Feature  agreements refactoring

---

pmp/app-elements/interventions/intervention-overview.html

- cp outputs now showing on interventions overview page

Intervention overview Cp Outputs fix 

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html

Fixing issues caused by Dexie not being updated with new data when an individual entry is updated

Dexie update on interventions details edit

---

pmp/app-elements/governments/government-details.html
pmp/app-elements/governments/government-plan-results.html

Validation for reference number was misplaced, adjusted it accordingly.
Also fixed validating work plan results, first result wasn’t being
parsed.

Validation and save fix

---

pmp/app-elements/governments/government-overview.html

Reverts unicef/etools-partnership-management#159

Revert "Government overview fixes"

---

pmp/app-elements/user-profile-dialog/user-profile-dialog.html

Supervisor now just a readonly paper input, displays string. Supervisees element moved one level in to fix styling.

Supervisor, supervisees display fix

---

pmp/app-elements/interventions/expected-results/ram-indicator-selector.html
pmp/app-elements/interventions/interventions-list.html

Spelling fixes 

---

pmp/app-elements/data-table/data-table-row.html
pmp/app-elements/interventions/interventions-list.html
styles/list-styles.html

- made the full title appear in the interventions list
- vertical allign not perfect

Intervetions Title Text cutting off

---

bower.json
pmp/app-elements/partners/partner-overview.html

-added total planned budget to partner overview inverventions list

Total budget on partners overview

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/interventions/monitoring-visits-list.html
styles/shared-styles.html

- Made statuses show in capital case

Misc small fixes

---

pmp/app-config/etools-app-config.html
pmp/app-elements/data-table/data-table-row.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/app-elements/governments/governments-list.html
pmp/pages/page-governments.html

- made the goverments list refresh its data from dexie when an entry is edited

Governments list refresh after item edited 

---

pmp/pages/page-agreements.html
pmp/pages/page-governments.html
pmp/pages/page-interventions.html

IE11 fix for add new agreement, add new intervention and add new government buttons.

Fix  ie add btns

---

pmp/app-elements/partners/partners-list.html

- Made the name wrap to a new line if too long

Fixed partners list display issue/ trello task su86O2TE 

---

pmp/app-config/etools-app-config.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/interventions/expected-results/result-link-lower-results.html
pmp/app-elements/interventions/intervention-expected-results.html
pmp/app-elements/partners/partners-list.html

https://github.com/unicef/etools-issues/issues/27

fix(cp indicators): add indicator fields baseline and target value must depend on indicator type

---

pmp/app-behaviors/ajax-server-errors-behavior.html
pmp/app-elements/common-elements/etools-form-element-wrapper.html
pmp/app-elements/governments/government-details.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/interventions/intervention-data/monitoring-visits-data.html
pmp/app-elements/interventions/intervention-fund-reservations.html
pmp/app-elements/interventions/intervention-planned-budget.html
styles/shared-styles.html

* still needs readonly style update

intervention planned budget values as currencies

---

pmp/app-elements/governments/governments-data/governments-list-data.html
pmp/app-elements/governments/governments-list.html

- fixes issue with government data not loading properly

Governments list fix  

---

pmp/app-elements/data-table/data-table-column.html
pmp/app-elements/governments/government-details.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/governments-list.html
pmp/pages/page-governments.html
styles/list-styles.html

- made curreny align to the right
- fixed issue with status box out of frame

Govt overview fixes 

---

pmp/app-elements/interventions/intervention-planned-budget.html

connects unicef/etools-issues#130

Intervention total budget 

---

pmp/app-shell.html

fixed console warning: 'Could not find style data in module named '

fixed missing style console warning

---

pmp/app-elements/interventions/expected-results/result-link-lower-results.html

Fixes unicef/etools-issues#125

Make lower level output required

---

bower.json
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/pages/page-interventions.html

connects unicef/etools-issues#236

fix(planned budget): validation error fix

---

pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/partners/partners-list.html
styles/list-filter-styles.html

- created a stylesheet for list filters
- connects unicef/etools-issues#233

Added list filter styles 

---

pmp/app-behaviors/lists-common-behavior.html
pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/partners/partners-list.html

- Set default lists page size to 10 instead of 5
- connects unicef/etools-issues#39

Set default lists size to 10

---

pmp/app-behaviors/common-general-behavior.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/monitoring-visits-list.html
pmp/app-elements/partners/partner-overview.html

- moved a recurring date function to the common behavior

moved date formatting function to the common behavior 

---

gulpfile.js
index.html

- fixed icon urls
- added JsHint to gulp linting script

Misc updates 

---

pmp/app-behaviors/esmm-missing-options/missing-cp-outputs-behavior.html
pmp/app-behaviors/esmm-missing-options/missing-signed-by-unicef-users-behavior.html
pmp/app-config/etools-app-config.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/expected-results/ram-indicator-selector.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html
pmp/app-elements/interventions/intervention-review-and-sign.html
pmp/app-elements/static-common-data/dropdowns-pmp-data.html
pmp/app-elements/static-common-data/redux-behaviors/common-static-data-redux-behavior.html

connects unicef/etools-issues#203
connects unicef/etools-issues#245
connects unicef-polymer/etools-searchable-multiselection-menu#60

Feature request esmm not found options

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-sector-locations.html
pmp/app-elements/user-profile-dialog/user-profile-dialog.html
pmp/pages/page-interventions.html

- connects unicef/etools-issues#244

Intervention - send only modified fields on save

---

pmp/app-elements/agreements/agreement-amendment-types.html
pmp/app-elements/agreements/agreement-amendments.html
pmp/app-elements/agreements/agreement-details.html

Add Amendment Validations:
- Signed Date can not be in the future
- Attachment is required
- connects unicef/etools-issues#180

Agreement amendments validations - frontend

---

pmp/pages/page-interventions.html

- On save intervention send only the modified items from the array of expected results/ indicators
- connect unicef/etools-issues#247

Intervention - Send only modif indicators

---

pmp/pages/page-interventions.html

- connect unicef/etools-issues#248

Intervention - attachment file type bug

---

bower.json
pmp/app-behaviors/notification-toasts-behavior.html
pmp/app-shell.html
styles/page-layout-styles.html

* IE11 "Unspecified error" fix
* toast notification style update for IE11

IE11 issues fix

---

pmp/app-behaviors/object-databind-behavior.html
pmp/app-elements/governments/government-details.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/government-plan-results.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/app-elements/governments/governments-data/governments-list-data.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/intervention-review-and-sign.html
pmp/app-elements/interventions/intervention-sector-locations.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/static-common-data/country-programmes-data.html
pmp/app-elements/static-common-data/dropdowns-pmp-data.html
pmp/app-elements/static-common-data/dropdowns-static-data.html
pmp/app-elements/static-common-data/locations-data.html
pmp/app-elements/static-common-data/offices-data.html
pmp/app-elements/static-common-data/sections-data.html
pmp/app-elements/static-common-data/sectors-data.html
pmp/app-elements/static-common-data/unicef-users-data.html
pmp/app-elements/user-profile-dialog/user-profile-dialog.html

- Remove mappings from the app
- closes unicef/etools-issues#251

Normalized redux data

---

pmp/app-elements/partners/partners-list.html

connects unicef/etools-issues#205

feature(partners list): add hidden attribute in export params regardless it's value

---

pmp/app-elements/interventions/intervention-planned-budget.html

connects unicef/etools-issues#280

fix(planned budget): restore local currency to USD

---

pmp/app-elements/partners/assessments-items.html
pmp/app-elements/partners/partner-details.html

connects unicef/etools-issues#210

Feature label fixes

---

pmp/app-behaviors/common-general-behavior.html
pmp/app-elements/partners/partner-details.html
pmp/app-elements/partners/partner-overview.html

- connects unicef/etools-issues#178

Partner details-change a label to 'Core Values Last Assessment Date'

---

pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html

- Fix for dropdown selected values not being reset when navigating from an existing intervention to a new intervention
- connects unicef/etools-issues#298

Intervention details dropdowns fixes

---

pmp/app-elements/interventions/intervention-details.html

- connects unicef/etools-issues#297

Fix Intervention validation inconsistency

---

pmp/app-shell.html

connects unicef/etools-issues#214

Fix footer position non ie

---

pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/pages/page-governments.html
scripts/polyfils/es6-polyfils.html

connects unicef/etools-issues#312

fix(new government): fix page freeze after the user try to duplicate a ref nr

---

pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/interventions/intervention-status.html
pmp/app-elements/partners/partner-status.html

connects and closes unicef/etools-issues#317

Fix multiple dialogs peristance issue

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/intervention-review-and-sign.html

- fix PRC Document ghosting issues
- connects unicef/etools-issues#323

Fix intervention ghosting issues

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/intervention-review-and-sign.html

Revert changes made here :
https://github.com/unicef/etools-partnership-management/pull/270
because the uploaded file is no longer displayed on UI

Revert fix for #323

---

pmp/app-elements/interventions/intervention-expected-results.html

refactoring : remove unused code

Cleanup code

---

pmp/app-elements/interventions/intervention-details.html
pmp/pages/page-interventions.html

- removed population focus
- connects unicef/etools-issues#309
- closes unicef/etools-issues#309

feature(remove-population-focus)

---

pmp/pages/page-agreements.html

- fixed issue with ammendments section appearing on the new agreements page

Fix agrements ammendments on new page

---

pmp/pages/page-governments.html

- made the overview page and link not appear on the new govt page

Fix overview on new govt page 

---

pmp/app-elements/partners/partner-overview.html

- updated to new data format
- total planned budget now displaying ok
- connects unicef/etools-issues#333
- closes unicef/etools-issues#333

Fix planned budget display 

---

pmp/app-elements/interventions/intervention-attachments.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-review-and-sign.html

I'll merge this directly since the error is blocking testing on the dev server

Fix bundled status error

---

pmp/app-shell.html

linting fixes

---

pmp/app-elements/interventions/intervention-sector-locations.html

connects unicef/etools-issues#345

Fix Intervention unique sector validation

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/intervention-review-and-sign.html

- connects unicef/etools-issues#323
- closes unicef/etools-issues#323

Fix etools-single-file ghosting issues

---

pmp/app-elements/countries-dropdown/countries-dropdown.html
pmp/app-elements/data-refresh-dialog/data-refresh-dialog.html
pmp/app-elements/page-header/page-header.html
pmp/app-menu/app-sidebar-menu.html
pmp/app-shell.html

Restore refresh data button to fit the other apps design consistency.

feature(data refresh): change refresh btn design

---

pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/agreements/agreement-data/agreement-list-data.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/app-elements/governments/governments-data/governments-list-data.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-data/interventions-list-data.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/app-elements/partners/partners-data/partners-list-data.html

- connects unicef/etools-issues#359
- closes unicef/etools-issues#359

Dexie data updates

---

pmp/app-behaviors/lists-common-behavior.html
pmp/app-behaviors/object-databind-behavior.html
pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/governments/government-details.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/government-plan-results.html
pmp/app-elements/governments/governments-data/government-intervention-item-data.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/partners/partners-list.html
pmp/app-shell.html
pmp/pages/page-agreements.html
pmp/pages/page-governments.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html

connects unicef/etools-issues#351

feature(page loading): improved page loading, disable-upgrade attribute removed 

---

pmp/app-elements/partners/partner-details.html

- Fixed issue with invisible overflowing buttons on single-file input
- connects unicef/etools-issues#362
- closes unicef/etools-issues#362

Fix-single-file-buttons-issue

---

pmp/app-elements/partners/assessments-items.html
pmp/app-elements/partners/partner-details.html

- added an error if the user selects a future date for the assesment date
- connects unicef/etools-issues#204
- closes unicef/etools-issues#204

Add assessment future date error message 

---

pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/governments/government-overview.html
pmp/app-elements/governments/governments-list.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/interventions/monitoring-visits-list.html
pmp/app-elements/partners/partners-list.html

- fix the issue with certain elements on lists not being vertically aligned on ie 
- connects unicef/etools-issues#360
- closes unicef/etools-issues#360

Fix list vertical alignment on IE

---

pmp/app-elements/agreements/agreements-list.html
styles/app-theme.html
styles/list-filter-styles.html

- fixed dropdown vertical alignment issues

Fix ie11 input styling issues 

---

bower.json
pmp/app-elements/interventions/expected-results/ram-indicator-selector.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/intervention-planned-visits.html
pmp/app-elements/interventions/intervention-sector-locations.html
pmp/app-elements/interventions/interventions-list.html
styles/shared-styles.html

connects unicef/etools-issues#348

Intervention details - use new version of single select dropdown

---

bower.json
pmp/app-elements/agreements/agreement-amendment-types.html
pmp/app-elements/agreements/agreement-details.html

connects unicef/etools-issues#350

Agreement details - use new dropdown version

---

bower.json
pmp/app-elements/partners/assessments-items.html

connects unicef/etools-issues#385

Partner details - use new version of single select dropdown

---

pmp/app-elements/partners/partners-list.html

- fixed issue with partners list filters not showing any options on first load
- connects unicef/etools-issues#417

Fix partners list filters 

---

pmp/app-menu/app-sidebar-menu.html
pmp/pages/page-interventions.html

connects unicef/etools-issues#428

PD/SSFA -remove ToR from name

---

bower.json
pmp/app-behaviors/repeatable-data-sets-behavior.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/data-refresh-dialog/data-refresh-dialog.html
pmp/app-elements/interventions/intervention-status.html
pmp/app-elements/partners/new-partner-dialog.html
pmp/app-elements/partners/partner-status.html
styles/app-mixins.html

- connects unicef/etools-issues#480

Fix dialogs padding

---

pmp/app-elements/interventions/fund-reservations-display.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/monitoring-visits-list.html
styles/table-styles.html

- connect unicef/etools-issues#502

Fund reservations display

---

pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html

- connects unicef/etools-issues#499

Intervention-Add red stars to mandatory fields

---

pmp/app-elements/interventions/intervention-status.html

- removed internvetion cancel action
- connects unicef/etools-issues#495

Remove intervention cancel action 

---

pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html

All planned budged fields are editable in draft (& new) status; in signed status only unicef cash field is editable

Planned budget edit mode updates

---

pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-status.html

- unsuspend working
- fixed icon issues on agreements page
- connects unicef/etools-issues#508

Agreements and intervention unsuspend 

---

pmp/app-elements/common-elements/etools-single-file.html
pmp/app-elements/partners/assessments-items.html

- updated array item selectors on observer method
- connects unicef/etools-issues#486

refactor array item observers 

---

pmp/app-elements/interventions/interventions-list.html
styles/required-field-styles.html

- fixed an issue with starred labels going to far to the right on ie11
- removed a misplaced closing tag
- connects unicef/etools-issues#520

IE11 labels fix 

---

bower.json
pmp/app-behaviors/list-filters-behavior.html
pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/interventions/interventions-list.html

- fixed an issue with date filters not showing the selected value on IE11
- connects unicef/etools-issues#520

Fix ie11 list filter date selectors 

---

pmp/app-elements/partners/partner-overview.html

- connect unicef/etools-issues#524

Add Actual column to partner Overview

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/pages/page-interventions.html

- connect unicef/etools-issues#531

Fix planned budget being sent on save if not modif

---

pmp/app-behaviors/lists-common-behavior.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/interventions/intervention-data/interventions-list-data.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/interventions-list.html

* all lists filters checked and fixed
* planned budget unicef cash display in currency format
* code cleanup (for ag/pd active statuses)

code cleanup, pd list filters fix, unicef cash display format fix

---

pmp/app-elements/partners/assessments-items.html

- fixed an error caused by an empty value from the back-end
- connects unicef/etools-issues#540

Fix assesment items error 

---

bower.json
pmp/app-elements/partners/new-partner-dialog.html
styles/app-mixins.html

- connects unicef/etools-issues#529

Remove scroll from new partner dialog / ie11 fix

---

pmp/app-elements/agreements/generate-PCA-dialog.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html

- connects unicef/etools-issues#536
Q. what lang parameter should be sent for 'IFRC English' and 'IFRC French'? @robertavram, @ntrncic? 
Also Portuguese template doesn't work as in the  'partners/pca' folder the template is spelled 'portugese'

Fix pca template lang param

---

pmp/app-elements/etools-status/etools-action-button.html

- updated the styling, made the dropdown much wider
- has problems on ie11, a scrollbar
- connects unicef/etools-issues#538

Etools-action-button dropdown styling update 

---

pmp/app-config/etools-app-config.html
pmp/app-elements/interventions/intervention-data/monitoring-visits-data.html
pmp/app-elements/interventions/monitoring-visits-list.html

- removed global loading from monitoring visits section
- added localised loading overlay for monitoring visits
- connects unicef/etools-issues#544

Monitoring visits loading

---

pmp/app-behaviors/esmm-missing-options/missing-dropdown-options-behavior.html
pmp/app-elements/agreements/agreement-details.html

- connects unicef/etools-issues#542

Agreement editable & hidden fields update

---

pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/interventions/intervention-status.html

- made the lists redraw from dexie on status changes
- connects unicef/etools-issues#454

Reload lists on status change 

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/interventions-list.html

- connects unicef/etools-issues#460

Intervention list - collapsable details update

---

pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html
pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/partners/partner-overview.html

- connects unicef/etools-issues#551

Update important-warning attribute usage on etool-info-tooltip

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-status.html
pmp/pages/page-interventions.html

- connects unicef/etools-issues#552

Fix not being able to supsend/terminate a signed intervention 

---

pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html
pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/partners/partner-overview.html
styles/shared-styles.html

- connects unicef/etools-issues#553

Fix Fr validation tooltip display issues

---

pmp/app-behaviors/notification-toasts-behavior.html
pmp/app-elements/partners/assessments-items.html
pmp/app-shell.html
styles/app-theme.html

- connects unicef/etools-issues#555

Update toast style

---

pmp/pages/page-interventions.html

- connects unicef/etools-issues#566

Show error messages from intervention.metadata.error_msg

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/interventions/intervention-status.html
pmp/pages/page-interventions.html

- connects unicef/etools-issues#560
- fixed issues with the status change buttons appearing even if such permissions are not in place

Fix status edit mode

---

bower.json
pmp/app-elements/agreements/agreement-amendments.html

-  connects unicef/etools-issues#556

Fix authorized officers blank and editable after add amendment and save

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/common-elements/etools-form-element-wrapper.html
pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/intervention-status.html
pmp/pages/page-interventions.html
styles/required-field-styles.html

- connects unicef/etools-issues#562

Agreement with hidden partner fix

---

pmp/app-elements/agreements/agreement-details.html
pmp/pages/page-agreements.html

- connect unicef/etools-issues#565, unicef/etools-issues#568

Signed By fields validations

---

bower.json
pmp/pages/page-interventions.html

- connects unicef/etools-issues#567
TODO - version for etools-file

Readonly intervention attachments when no Save btn

---

pmp/app-elements/partners/assessments-items.html

- connects unicef/etools-issues#571

Fix partner assesment error when no file uploaded

---

pmp/app-elements/etools-status/etools-action-button.html

- connects unicef/etools-issues#559

Fix scroll shown on iIE11 for action-button dropdown

---

pmp/app-elements/partners/partner-overview.html

- connect unicef/etools-issues#582

Fix planned budget in partner overview

---

pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html
pmp/app-elements/interventions/intervention-details.html
pmp/pages/page-interventions.html

Remove console logs added to investigate a bug that reproduced only on dev

Remove console logs

---

bower.json
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/countries-dropdown/countries-dropdown.html
pmp/app-elements/etools-status/pmp-status-behavior.html
pmp/app-elements/interventions/behaviors/modified-intervention-fields-behavior.html
pmp/app-elements/interventions/behaviors/save-intervention-behavior.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-form/agreement-selector.html
pmp/app-elements/partners/partner-details.html
pmp/pages/page-agreements.html

- connects unicef/etools-issues#570

Avoid header overlapping dropdown content

---

pmp/pages/page-agreements.html

- connects unicef/etools-issues#593

Fix create agreement error

---

bower.json
pmp/app-elements/interventions/intervention-attachments.html
pmp/pages/page-agreements.html

- connect unicef/etools-issues#591

Fix attachments toast msg cut off

---

pmp/app-elements/partners/partner-overview.html
pmp/pages/page-agreements.html

- connects unicef/etools-issues#601

Fix partner overview not displaying

---

pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/pages/page-partners.html

- connects unicef/etools-issues#594
- fixed issues with server errors not being displayed on the partners detail page

feature(fix-partner-delete):

---

bower.json
pmp/app-elements/etools-status/etools-action-button.html

- connects unicef/etools-issues#588

IE 11 issues 

---

pmp/app-elements/agreements/generate-PCA-dialog.html
pmp/app-elements/partners/partners-data/partners-list-data.html
pmp/pages/page-agreements.html

- connects unicef/etools-issues#598

Fix unable to search by vendor number that has letters in it

---

pmp/app-elements/interventions/intervention-planned-budget.html

- connects unicef/etools-issues#461

IE 11 Fix currency

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/partners/partners-data/partner-staff-members-data.html
pmp/pages/page-agreements.html

- connects unicef/etools-issues#581

Deactivated partner contacts fix

---

pmp/app-shell.html

- connects unicef/etools-issues#613

Ie11- 3 line toast msg issue

---

pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html
pmp/app-elements/interventions/behaviors/modified-intervention-fields-behavior.html
pmp/app-elements/interventions/intervention-details.html

- connects unicef/etools-issues#609

Contingency PD feature

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/etools-status/pmp-status-behavior.html
pmp/app-elements/partners/partner-status.html

- connects unicef/etools-issues#615
- Fixes an issue with the status not being positioned properly on details pages on first load and before any scrolling

Fix sticky status positioning issue 

---

pmp/pages/page-agreements.html

- fixes an issue with not being able to suspend or terminate an agreement
- connects unicef/etools-issues#617

Fix agreements suspend action 

---

pmp/app-elements/partners/partners-data/partners-list-data.html
pmp/app-elements/partners/partners-list.html
pmp/pages/page-partners.html

- connects unicef/etools-issues#604
- added some code to re-fire partners-list-data in order to reload the partners data stored in redux

Remove deleted partners from dropdowns

---

pmp/pages/page-partners.html

- connects unicef/etools-issues#623

Fix error when navigating to PD from Partner Overview

---

pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/interventions/intervention-details.html
pmp/pages/page-agreements.html

- connect unicef/etools-issues#637

Hide start/end date when contingency pd is on

---

pmp/app-elements/data-refresh-dialog/data-refresh-dialog.html

- connects unicef/etools-issues#657

Fix redirect after Partners dexie refresh

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-overview.html

- connects unicef/etools-issues#622

Fix intervention overview locations

---

pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/etools-status/pmp-status-behavior.html
pmp/app-elements/interventions/intervention-status.html
pmp/app-elements/partners/partner-status.html

- fix an issue with the actions button on the status element showing Save action even if editMode is false
- connects unicef/etools-issues#679

Fix persistent status actions

---

pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html

Fixed an error with  errors persisting in the fund-reservations panel even though the problem in details was fixed
this connects to unicef/etools-issues#694

Fix frs inconsistency error

---

pmp/app-behaviors/ajax-server-errors-behavior.html
pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/notification-toasts/notification-toasts-style.html
pmp/app-elements/partners/assessments-items.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/pages/page-partners.html

- connects unicef/etools-issues#690
- connects unicef/etools-issues#691

Format error for add partner with null partner_type & refactoring

---

pmp/app-shell.html
pmp/pages/page-interventions.html

- connects unicef/etools-issues#683

Fix active tab 

---

bower.json
pmp/app-elements/interventions/intervention-data/intervention-item-data.html

- connects unicef/etools-issues#673

Update agreement after intervention status change

---

pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/etools-status/pmp-status-behavior.html
pmp/app-elements/interventions/intervention-status.html

- updated dialog messages
- connects unicef/etools-issues#671

Update status warning messages 

---

pmp/app-elements/interventions/behaviors/save-intervention-behavior.html

- connects unicef/etools-issues#698

Fix save after refresh on Review&Sign tab 

---

pmp/pages/behaviors/page-utils-behavior.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html

- fixed an issue with list filters getting reset
- connects unicef/etools-issues#701

Fix list filters reset issue 

---

bower.json
pmp/app-elements/agreements/agreement-amendments.html

- updated template url to conform to the new extension being used
- updated esmm version
- connects unicef/etools-issues#709

fix(ammendment-template-url):

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/partners/behaviors/partner-staff-members-data-behavior.html

- fixed an issue with deactivated officers being present in the dropdown from the pd details page
- connects unicef/etools-issues#722

Fix partner officers on PD details page 

---

.gitignore
gulpfile.js
package.json

added a gulp task that exports the git revision number to a external file

Gulp revision number output 

---

pmp/app-elements/partners/staff-members.html

- made the position mandatory when adding a partner contact
- connects unicef/etools-issues#724

Add partner contact position validation

---

pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html

-  the details pages now scroll to top on server errors
- connects unicef/etools-issues#731

Scroll to top on server errors 

---

pmp/app-elements/partners/assessments-items.html

- updated error message
- connects unicef/etools-issues#734

Fix assessment error message 

---

pmp/app-elements/interventions/intervention-overview.html

- fixed an issue with the sectors not showing on the interventions overview
- connects unicef/etools-issues#669

Fix sectors on pd overview

---

pmp/app-elements/partners/partner-status.html

- fixed an issue with the partners status text oveflowing on IE
- connects unicef/etools-issues#739

Fix partners overflowing status text 

---

pmp/app-shell.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html

- fixed an issue with the lists being scrolled to bottom
- connects unicef/etools-issues#738

Fix list scroll position 

---

pmp/app-elements/interventions/intervention-status.html

- fixed a status on the pd page
- connects unicef/etools-issues#740

Fix PD ended status 

---

pmp/app-elements/agreements/agreement-status.html

- remove unsuspend action from SSFAs
- connects unicef/etools-issues#725

Fix agreement unsuspend action 

---

pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html

- fixed FR Amount on intervention fund reservations
- connects unicef/etools-issues#741

Fix implementation status numbers 

---

.jshintrc
bower.json
pmp/app-config/app-dexie-db-config.html
pmp/app-elements/interventions/expected-results/cluster-indicator.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/intervention-attachments.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/partners/behaviors/partner-staff-members-data-behavior.html
pmp/app-elements/static-common-data/redux-behaviors/common-static-data-redux-behavior.html
pmp/pages/page-agreements.html
pmp/pages/page-partners.html

- fixed missing behavior errors
- connects unicef/etools-issues#727

Linting fixes 

---

pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/interventions/intervention-status.html
pmp/pages/page-interventions.html

- you can now add ammendments to ended or closed PDs
- connects unicef/etools-issues#745

Intervention attachments on ended or closed 

---

pmp/app-behaviors/ajax-errors-parser-behavior.html

- connects unicef/etools-issues#748

Parse nested errors arrays

---

pmp/app-elements/settings/disaggregation-list.html

- connects unicef/etools-issues#753

Disaggregation list pagination

---

pmp/app-behaviors/ajax-errors-parser-behavior.html
pmp/app-behaviors/ajax-server-errors-behavior.html
pmp/app-elements/interventions/expected-results/ram-indicator-selector.html
pmp/app-elements/interventions/monitoring-visits-list.html
pmp/app-elements/user-profile-dialog/user-profile-data/user-profile-data.html

- fixed an issue with html markup showing up in toast messages
- connects unicef/etools-issues#736

Fix toast server errors 

---

pmp/app-elements/interventions/intervention-status.html

- added missing suspend and terminate actions on PD status 
- connects unicef/etools-issues#775

Fix missing suspend and terminate actions 

---

pmp/app-elements/interventions/behaviors/save-intervention-behavior.html

- updated warning message
- connects unicef/etools-issues#763

Update pd status change warning text 

---

pmp/app-elements/interventions/expected-results/behaviors/results-behavior.html

- connects unicef/etools-issues#781

Fix error on adding first Pd output or expected result

---

bower.json
pmp/app-elements/agreements/agreement-details.html

- removed the generate PCA button from the new agreements page to prevent a back-end error
- connects unicef/etools-issues#777

fix(generate-pca-error);

---

pmp/app-elements/users-data/user-data.html

- fixed an issue with unauthorized users not being redirected to login
- connects unicef/etools-issues#789

Fix user login redirect 

---

pmp/app-elements/interventions/expected-results/cluster-indicator.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/intervention-sector-locations.html

- Changed labels from  "sector" to "section"
- connects unicef/etools-issues#762

Fix sector labels

---

pmp/app-elements/data-refresh-dialog/data-refresh-dialog.html

- fixed an issue with list data not being populated after refreshing from the dialog
- connects unicef/etools-issues#793

Fix data refresh issues 

---

pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html

- fixed an issue with the total fr amount not being the sum of entries
- connects unicef/etools-issues#780

Fix PD overview amount 

---

pmp/app-elements/interventions/behaviors/save-intervention-behavior.html
pmp/app-elements/interventions/intervention-review-and-sign.html

- fixed an issue with the PRC review document not being sent to the API
- connects unicef/etools-issues#794

Fix prc document upload

---

pmp/app-elements/interventions/intervention-status.html

- updated status warning text
- connects unicef/etools-issues#800

Fix status warning text

---

pmp/app-elements/data-refresh-dialog/data-refresh-dialog.html

- fixed errors from the browser console
- connects unicef/etools-issues#793

Fix data refresh errors

---

pmp/app-elements/interventions/expected-results/ram-indicator-selector.html
pmp/app-elements/interventions/expected-results/result-link-lower-results.html

- fixed an issue with the search field not being accesible
- connects unicef/etools-issues#803

Fix esmm header overlap

---

bower.json
pmp/app-behaviors/esmm-missing-options/missing-dropdown-options-behavior.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/expected-results/ram-indicator-selector.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-review-and-sign.html

connects unicef/etools-issues#808

fix(missing options requests): dropdown version updates to fix v2.2.6 issues

---

bower.json
pmp/app-elements/interventions/expected-results/indicator-dialog.html

- fixed an issue with the dialog not being resized once naigation has occured
- connects unicef/etools-issues#791

Fix indicator dialog size issues

---

pmp/app-config/app-endpoints-behavior.html

- removed caching for user endpoint
- fixed an issue with permission changes not propagating to the application immediately
- connects unicef/etools-issues#670

Fix permissions update issue

---

pmp/app-elements/validators/required-and-not-future-date-validator.html

- fixed an issue with date validators blocking the creation of a new intervention

Fix review and sign required date issue

---

pmp/app-elements/interventions/intervention-form/agreement-selector.html

show partner name and agreement in readonly mode in case partner was hidden or is not CSO

Fix pd/ssfa details agreement selector

---

pmp/app-elements/etools-status/pmp-status-behavior.html
pmp/app-elements/partners/partner-status.html
styles/app-theme.html
styles/page-layout-styles.html

polymer css variables are not recognized by media queries

fix status responsive issue

---

pmp/app-behaviors/ajax-errors-parser-behavior.html
pmp/app-behaviors/ajax-server-errors-behavior.html

- connects unicef/etools-issues#831

Handle http request error 413

---

bower.json
pmp/app-elements/interventions/grouped-locations-dialog.html
pmp/app-elements/interventions/intervention-details.html

- connects unicef/etools-issues#809
TODO - endpoint for adminLevels , maybe in a future PR

Group locations by admin level a.k.a location type

---

pmp/app-elements/interventions/expected-results/cluster-indicator.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/expected-results/result-link-lower-results.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-expected-results.html

- connects unicef/etools-issues#848

Update locations and clusters after indicators change

---

bower.json
pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/reports/reporting-requirements.html

- updated row shadows on data tables
- updatd fund reservations table

Update data table styles 

---

pmp/app-elements/interventions/grouped-locations-dialog.html
pmp/app-elements/settings/disaggregation-list.html
pmp/app-elements/static-common-data/behaviors/dropdowns-static-data.html
pmp/app-elements/static-common-data/redux-behaviors/common-static-data-redux-behavior.html

- connects unicef/etools-issues#809

Grouped locations - integrate with adminLevels endpoint

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html

- connects unicef/etools-issues#868

Fix update sections in intervention list after intervention Save

---

bower.json
pmp/app-elements/interventions/expected-results/behaviors/results-behavior.html
pmp/app-elements/interventions/expected-results/result-cp-output-and-ram-indicators.html

- connects unicef/etools-issues#869
TODO update dropdown version

Fix autovalidation triggering too soon

---

pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/interventions-list.html

- connects unicef/etools-issues#866

No fr warning tooltips for closed PDs

---

pmp/app-elements/interventions/intervention-planned-budget.html

- connects unicef/etools-issues#838

Planned Budget labels update

---

bower.json
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/app-elements/interventions/reports/reporting-requirements.html
styles/page-layout-styles.html

- fixed an issue with the planned budget element having 0 height on IE
- connects unicef/etools-issues#871

Fix planned budget on IE

---

pmp/app-behaviors/date-behavior.html

- fixed an issue with the lists not showing any data
- connects unicef/etools-issues#878

Fix ie11 list issue

---

pmp/app-elements/countries-dropdown/countries-dropdown.html
pmp/app-elements/users-data/user-data.html

- connects unicef/etools-issues#830

Fix change country from admin 

---

pmp/app-behaviors/list-data-behavior.html

- fixed an issue with the list data not refreshing automatically on expiry
- connects unicef/etools-issues#883

Fix automatic data refresh

---

pmp/app-config/app-endpoints-behavior.html
pmp/app-elements/interventions/reports/reporting-requirements-dialog.html
pmp/app-elements/reports/elems/report-rating-dialog.html
pmp/app-elements/reports/elems/report-reject-dialog.html
pmp/pages/page-reports.html

- added the report rating dialog prototype
- connects unicef/etools-issues#877

Feature reports page dialogs

---

pmp/app-config/app-endpoints-behavior.html
pmp/app-config/app-requests-tokens-behavior.html
pmp/app-elements/reports/elems/reports-display-list.html
pmp/app-shell.html

jwt-token-requests

---

pmp/app-elements/interventions/expected-results/behaviors/save-indicator-behavior.html
pmp/app-elements/interventions/expected-results/cluster-indicator.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
styles/shared-styles.html

- connects unicef/etools-issues#629

Cluster indicator changes

---

polymer.json

- fixed an issue with the settings page not rendering on internet explorer
- connects unicef/etools-issues#895

Fix settings page on ie

---

pmp/app-elements/interventions/intervention-planned-budget.html

- fixed an issue with planned budget currency not being aligned on ie
- connects unicef/etools-issues#871

Fix ie currency issue

---

pmp/app-elements/interventions/intervention-amendments.html
pmp/pages/page-interventions.html

- fixed an issue with the "other" field not having readonly styles applied
- connects unicef/etools-issues#829

Fix amendments style

---

pmp/app-elements/settings/disaggregation-list.html

- connects unicef/etools-issues#904

Disaggregation List style fix

---

pmp/app-elements/interventions/reports/reporting-requirements.html

- fixed an error with the invervention id missing from request URLs
- connects unicef/etools-issues#905

Fix reporting requirements endpoint error

---

pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html

- removed tooltips from the fund reservations
- connects unicef/etools-issues#902

Remove tooltips from review&sign

---

pmp/app-elements/interventions/interventions-list.html

- fixed an issue with not being able to filter exports by more than one status
- connects unicef/etools-issues#898

Fix csv download url

---

bower.json
pmp/app-behaviors/ajax-errors-parser-behavior.html
pmp/app-behaviors/ajax-server-errors-behavior.html
pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/partners/partners-data/partner-item-data.html
pmp/app-elements/reports/elems/behaviors/report-details-behavior.html
pmp/app-shell.html
pmp/pages/behaviors/page-utils-behavior.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html
pmp/pages/page-reports.html

- Made 4xx errors show the default message
- connects unicef/etools-issues#911

Update error handler

---

test/agreements/details.html
test/agreements/list.html
test/agreements/page.html
test/index.html
test/test-helpers/agreements-testing-helper.html
test/test-helpers/testing-utils.html

- connects unicef/etools-issues#353

Agreements tests refactoring

---

pmp/app-elements/interventions/expected-results/behaviors/save-indicator-behavior.html

- connects unicef/etools-issues#926

Improve indicators validation

---

pmp/app-config/app-endpoints-behavior.html
pmp/app-config/app-endpoints.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/countries-dropdown/countries-dropdown.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-review-and-sign.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/page-header/page-header.html
pmp/app-elements/user-profile-dialog/user-profile-data/user-profile-data.html
pmp/app-elements/users-data/user-data.html

-connects unicef/etools-issues#456
Backend changes ( etools-issues#921) done for this task: 
1.  For endpoint /api/v2/dropdowns/pmp in the 'signed_by_unicef_users' I need a rename of properties from user_id & full_name to id & name 
2. We have to upgrade to v3 for user endpoints. But v3 of this endpoint: /api/v3/users/country/ returns less data than the one we currently use /api/v2/users/country/. So please add the data returned by the v2 version to v3, as well, for endpoint /api/v3/users/country/

Update to user endpoints v3

---

pmp/app-elements/agreements/agreement-details.html
pmp/pages/page-agreements.html

- connects unicef/etools-issues#767

MOU agreement - hide authorized officers

---

pmp/app-elements/interventions/intervention-form/agreement-selector.html

- connects unicef/etools-issues#726

Intervention- remove MOU agreement from dropdown

---

pmp/pages/page-interventions.html

- fixed a console error on pd progress tab
- connects unicef/etools-issues#938

Fix pd progress errors

---

pmp/app-elements/interventions/intervention-form/agreement-selector.html

- fixed a console error related to accessing a property of undefined
- connects unicef/etools-issues#930

Fix console errors

---

pmp/app-config/app-endpoints-behavior.html

- connect unicef/etools-issues#456

Small fix for migrating to v3 of user endpoints

---

pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/reports/reporting-requirements.html

- added ability to edit or view reporting periods based on the permissions matrix
- connects unicef/etools-issues#925

Fix reporting periods permissions

---

pmp/app-elements/interventions/intervention-details.html
pmp/pages/page-interventions.html

- fixed an issue with tab underlines not updating
- fixed an esmm-related console error
- connects unicef/etools-issues#967

Fix interventions tabs issue

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/intervention-planned-visits.html

- fixed an issue with new agreements not showing draft status
- fixed an issue with planned visits being deletable after a new intervention was created
- connects unicef/etools-issues#1010

Fix planned visits delete issue

---

pmp/app-config/environment-flags-behavior.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/static-common-data/behaviors/environment-flags.html

- fixed an issue with indicators data not updating in the PD details
- connects unicef/etools-issues#1023

Fix interventions data update issues

---

pmp/app-behaviors/common-behavior.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html

- fixed an issue with unmodified fields being sent along with PATCH requests
- removed unused method
- connects uniecef/etools-issues#1022

Fix intervention patch issues

---

pmp/app-behaviors/pagination-behavior.html
pmp/app-behaviors/utils-behavior.html
pmp/app-config/app-endpoints-behavior.html
pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/common-elements/etools-progress-bar.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/static-common-data/redux-behaviors/common-static-data-redux-behavior.html
pmp/pages/page-reports.html

- changed incompatible function calls
- connects unicef/etools-issues#1033
- connects unicef/etools-issues#1031
- connects unicef/etools-issues#1032

Fix ie11 problems 

---

pmp/app-elements/interventions/reports/reporting-requirements.html

- fixed an issue with reporting requirements not being editable
- connects unicef/etools-issues#1070
- connects unicef/etools-issues#1071

Fix reporting requirements issues

---

bower.json
express.js

- fixed issues with index being served instead of missing static files
- connects unicef/etools-issues#1041

Fix built version 404 issues

---

pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html
pmp/app-elements/interventions/intervention-details.html

- fixed an issue with flat locations not being editable in new pd
- connects unicef/etools-issues#1065

Fix locations edit issue

---

pmp/app-elements/interventions/reports/reporting-requirements.html

- removed add reporting period button from new PD page
- connects unicef/etools-issues#1059

Fix reporting periods add button

---

bower.json
pmp/app-elements/page-header/page-header.html
pmp/app-elements/user-profile-dialog/user-profile-data/user-profile-data.html

- on saving changes on user's own profile only modified data is being sent to the server
- connects unicef/etools-issues#939

Profile data updates

---

pmp/app-behaviors/list-filters-behavior.html
pmp/app-elements/agreements/agreement-data/agreement-list-data.html
pmp/app-elements/interventions/intervention-data/interventions-list-data.html

- changed filter logic to not show results from the selected date
- connects unicef/etools-issues#1088

Fix pd date filter issues

---

pmp/app-elements/interventions/grouped-locations-dialog.html
pmp/app-elements/interventions/intervention-details.html

- connects unicef/etools-issues#919

Grouped locations fix

---

bower.json
pmp/app-elements/agreements/agreements-list.html
pmp/app-elements/data-refresh-dialog/data-refresh-dialog.html
pmp/app-elements/etools-status/etools-action-button.html
pmp/app-elements/interventions/expected-results/cluster-indicator.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/interventions-list.html
pmp/app-elements/interventions/monitoring-visits-list.html
pmp/app-elements/interventions/progress/intervention-progress.html
pmp/app-elements/interventions/reports/reporting-requirements.html
pmp/app-elements/partners/assessments-items.html
pmp/app-elements/partners/partner-overview.html
pmp/app-elements/partners/partners-list.html
pmp/app-elements/reports/elems/reports-display-list.html
pmp/app-elements/reports/report-progress.html
pmp/app-elements/reports/report-summary.html
pmp/app-elements/reports/reports-list.html
pmp/pages/page-not-found.html
styles/risk-rating-styles.html
styles/shared-styles.html

- connects unicef/etools-issues#1102
- Replace paper-menu with paper-listbox and paper-material with paper-styles

Replace deprecated polymer elements

---

pmp/app-elements/partners/partner-overview.html

- changed hact data to line up with back-end changes
- connects unicef/etools-issues#1109

Fix partner hact data

---

bower.json

connects unicef/etools-issues#1112

currency input - query for iron-input fix

---

bower.json
pmp/app-behaviors/repeatable-data-sets-behavior.html
pmp/app-elements/interventions/edit-delete-actions.html
pmp/app-elements/interventions/expected-results/applied-indicator.html
pmp/app-elements/interventions/expected-results/behaviors/results-behavior.html
pmp/app-elements/interventions/expected-results/edit-delete-actions.html
pmp/app-elements/interventions/expected-results/result-link-lower-results.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-expected-results.html
styles/grid-layout-styles.html
styles/shared-styles.html

- connects unicef/etools-issues#1026

New design for expected results

---

bower.json
pmp/app-elements/interventions/expected-results/applied-indicator.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/expected-results/pd-lower-result-name.html
pmp/app-elements/interventions/expected-results/result-link-lower-results.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-expected-results.html
styles/shared-styles.html

- connects unicef/etools-issues#1026

Expected results design improvements

---

pmp/app-elements/interventions/expected-results/applied-indicator.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/interventions/intervention-expected-results.html

- Fix disaggregations display and add green border for cluster indicators in indicators modal
- connects unicef/etools-issues#1026

Results design additions

---

pmp/app-elements/environment-flags/environment-flags-behavior.html
pmp/app-elements/static-common-data/static-common-data.html

Add prp api env flag

---

pmp/app-behaviors/ajax-errors-parser-behavior.html
pmp/app-elements/common-elements/etools-error-messages-box.html
scripts/polyfils/es6-polyfils.html

- connects unicef/etools-issues#1128

Improve errors display

---

index.html
pmp/app-elements/static-common-data/redux-behaviors/common-static-data-redux-behavior.html
scripts/redux.html

- connects unicef/etools-issues#1137

Fix for 'Redux.createStore is not a function '

---

pmp/app-elements/common-elements/etools-tabs.html
pmp/app-elements/interventions/expected-results/behaviors/indicator-dialog-tabs-behavior.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/reports/elems/indicator-details.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html
pmp/pages/page-reports.html

connects unicef/etools-issues#1125

Indicator dialog tabs update

---

pmp/app-elements/interventions/expected-results/behaviors/indicator-dialog-tabs-behavior.html
pmp/app-elements/interventions/intervention-expected-results.html

connects unicef/etools-issues#1139

Fix  pd details sections locations

---

pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html

- fixed edit issue on planned budget
- connects unicef/etools-issues#1140

Fix planned budget permissions issue

---

pmp/app-elements/interventions/expected-results/result-link-lower-results.html
pmp/app-elements/interventions/intervention-details.html

- connects unicef/etools-issues#1138

Fix See all locations link

---

pmp/app-elements/interventions/expected-results/applied-indicator.html
pmp/app-elements/interventions/expected-results/applied-indicators.html
pmp/app-elements/interventions/expected-results/behaviors/save-indicator-behavior.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/expected-results/result-link-lower-results.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-expected-results.html

Indicator fixes

---

pmp/app-elements/interventions/behaviors/save-intervention-behavior.html
pmp/app-shell.html
pmp/pages/behaviors/page-import-behavior.html
pmp/pages/behaviors/page-utils-behavior.html
pmp/pages/behaviors/subroute-behavior.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html
pmp/pages/page-reports.html

connects unicef/etools-issues#1125

Feature  subroute behavior

---

pmp/app-behaviors/scroll-control-behavior.html
pmp/app-shell.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html
pmp/pages/page-reports.html

- fixed issues with scolling to top after save
- related to clubhouse story nr. 1960

Fix scroll to top issues

---

pmp/app-elements/interventions/expected-results/behaviors/indicators-common-behavior.html
pmp/app-elements/interventions/expected-results/behaviors/save-indicator-behavior.html
pmp/app-elements/interventions/expected-results/non-cluster-indicator.html
pmp/app-elements/interventions/intervention-details.html

- connects unicef/etools-issues#1026

No of Pd outputs in panel title & small fixes

---

pmp/app-elements/agreements/agreement-details.html
pmp/app-elements/interventions/intervention-attachments.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-overview.html
pmp/app-elements/interventions/intervention-review-and-sign.html
pmp/app-elements/interventions/progress/intervention-progress.html
pmp/app-elements/interventions/reports/intervention-reports.html
pmp/app-elements/partners/partner-details.html
pmp/app-elements/partners/partner-overview.html
pmp/app-elements/reports/report-progress.html
pmp/app-elements/reports/report-summary.html
pmp/pages/behaviors/page-utils-behavior.html
pmp/pages/behaviors/subroute-behavior.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html
pmp/pages/page-partners.html

connects  unicef/etools-issues#1125

tab attached flag update, used to show the status sidebar

---

pmp/app-elements/reports/elems/reports-display-list.html
pmp/pages/behaviors/page-utils-behavior.html
pmp/pages/behaviors/subroute-behavior.html
pmp/pages/page-interventions.html
scripts/polyfils/es6-polyfils.html

- amendment mode now shows after page is attached
- connects unicef/etools-issues#1125

Amendment mode improvements

---

pmp/pages/page-reports.html

- added missing imports for reports page

Fix scroll control error

---

pmp/app-elements/interventions/intervention-planned-visits.html

- connects unicef/etools-issues#1147

Fix planned visits console error

---

pmp/app-elements/interventions/reports/intervention-reports.html
pmp/app-shell.html
pmp/pages/behaviors/subroute-behavior.html
pmp/pages/page-interventions.html

- connects unicef/etools-issues#1145

Fix lingering reports query string

---

pmp/pages/page-agreements.html

- agreements status was  not rendering
- connects unicef/etools-issues#1151

Fix missing agreement status

---

pmp/app-shell.html
pmp/modules/app-modules/agreements/agreements-module.html
pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/not-found/not-found.html
pmp/modules/app-modules/partners/partners-module.html
pmp/modules/app-modules/reports/reports-module.html
pmp/modules/app-modules/settings/settings-module.html
pmp/modules/layout/menu/app-sidebar-menu.html
pmp/modules/layout/menu/mixins/app-menu-mixin.html
pmp/modules/mixins/amendment-mode-mixin.html
pmp/modules/mixins/scroll-control-mixin.html

connects unicef/etools-issues#1020

app shell routing, other updates

---

pmp/modules/app-modules/mixins/intervention-page-tabs-mixin.html
pmp/modules/app-modules/mixins/module-common-mixin.html
pmp/modules/app-modules/mixins/module-routing-mixin.html
pmp/modules/mixins/ajax-server-errors-mixin.html
pmp/modules/mixins/repeatable-data-sets-mixin.html
pmp/modules/mixins/scroll-control-mixin.html
pmp/modules/user/user-data.html

connects unicef/etools-issues#1020

app modules routing anf common functionality + fire event in polymer 2 style updates

---

pmp/app-elements/settings/disaggregation-list.html

- connects unicef/etools-issues#1152

Fix disaggregations not displayed sometimes

---

pmp/app-shell.html
pmp/modules/app-modules/mixins/module-common-mixin.html
pmp/modules/app-modules/mixins/module-routing-mixin.html
pmp/modules/app-modules/not-found/not-found.html
pmp/modules/app-modules/partners/data/partner-item-data.html
pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/app-modules/partners/partners-module.html
pmp/modules/layout/components/etools-status/etools-action-button.html
pmp/modules/layout/menu/app-sidebar-menu.html
pmp/modules/layout/page-header.html
pmp/modules/mixins/ajax-errors-parser-mixin.html
pmp/modules/mixins/ajax-server-errors-mixin.html
pmp/modules/mixins/list-data-mixin.html
pmp/modules/mixins/lists-common-mixin.html
pmp/modules/mixins/repeatable-data-sets-mixin.html
pmp/modules/user/user-data.html

connects unicef/etools-issues#1020

Polymer 2 event handlers update 

---

pmp/app-elements/environment-flags/environment-flags-behavior.html
pmp/app-elements/environment-flags/environment-flags.html

- connects unicef/etools-issues#1152

Fix timing issue on settings page

---

pmp/app-elements/interventions/intervention-planned-visits.html

Planned visits-adjust validation

---

pmp/app-elements/interventions/intervention-planned-budget.html

connects to clubhouse issue 4387

pd currency init fix

---

pmp/app-elements/interventions/amendments/add-amendment-dialog.html
pmp/app-elements/interventions/amendments/intervention-amendments.html

-  fixed an issue with amendments being added to the PD
that was previously viewed
- connects to clubhouse issue 4435

Amendments to incorrect pd

---

pmp/app-config/app-constants.html
pmp/app-elements/partners/assessments-items.html
pmp/app-elements/partners/partner-financial-assurance.html

-Assessment Items no longer have a dropdown based on new requirements
-Fab removed from assessment items in place of a text button.
-New items added need to be placed on top of list
-Financial assurance engagements list is now sorted by date

Assessment items refactor, list sort on financial assurance

---

pmp/app-elements/interventions/amendments/intervention-amendments.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/pages/page-interventions.html

- fixed an issue with modified fields getting reset when
entering amendment mode
- removed add amendment button when interveiton has in_amendment: true
- added redirect to details when adding an amendment
- related to clubhouse issues 4405 4390 4398

Fix interventions amendments issues

---

pmp/app-elements/etools-status/etools-action-button.html
pmp/app-elements/interventions/expected-results/applied-indicator.html
pmp/app-elements/interventions/interventions-list.html
pmp/pages/page-interventions.html

Update PD export btn

---

pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html

locations field is not required on new pd page

---

pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-planned-budget.html
pmp/pages/page-interventions.html

Disable currency edit in amendment mode

---

pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html

frs warning fixes

---

pmp/app-config/app-endpoints.html
pmp/pages/page-interventions.html

Fix result exports link

---

pmp/app-config/app-user-permissions-behavior.html
pmp/app-elements/interventions/expected-results/indicator-dialog.html
pmp/app-elements/settings/disaggregation-list.html

- add disagregations button now only visible to PME users

Add disaggregations button for PME users only 

---

pmp/app-elements/agreements/agreement-details.html

Fix for https://app.clubhouse.io/unicefetools/story/1874/change-the-cp-structure-handling-in-agreements

add special cps to the list of agreement cps

---

pmp/app-config/app-endpoints.html
pmp/app-elements/agreements/agreement-data/agreement-item-data.html
pmp/app-elements/agreements/agreement-status.html
pmp/app-elements/etools-status/pmp-status-behavior.html
pmp/app-elements/interventions/intervention-data/intervention-item-data.html
pmp/app-elements/interventions/intervention-details.html
pmp/app-elements/interventions/intervention-status.html
pmp/app-shell.html
pmp/pages/page-agreements.html
pmp/pages/page-interventions.html

https://app.clubhouse.io/unicefetools/story/1894/delete-option-should-be-available-for-agreements-and-pds-in-draft-status-4-5
BE: https://github.com/unicef/etools/pull/1271

Delete agreements and PDs in draft status

---

pmp/modules/app-modules/settings/components/disaggregation-list.html
pmp/modules/user/user-permissions-mixin.html

- restricted non-PME users from adding disaggregations
- CH 4775

polymer2-add-disagregations-permissions:

---

pmp/app-shell.html
pmp/modules/user/user-data-mixin.html

- fixed an issue with profile request getting fired twice
- relates to CH 4785

Fix polymer2 duplicate profile requests

---

bower.json

the update to etools-searchable-multiselection-menu fixes an IE console error
the update to etools-profile-dropdown updates deprecated dropdowns inside the user profile dialog

updated pacakages versions

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/layout/components/etools-cp-structure.html

Port PR #784 to polymer 2
[ch1499]

Polymer2 expired cp 

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html
pmp/modules/app-modules/interventions/pages/details/components/grouped-locations-dialog.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/app-modules/interventions/pages/overview/components/fund-reservations-display.html
pmp/modules/app-modules/interventions/pages/overview/components/monitoring-visits-list.html
pmp/modules/app-modules/interventions/pages/overview/intervention-overview.html
pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/app-modules/interventions/pages/reports/intervention-reports.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/layout/components/etools-progress-bar.html
polymer.json

Migrate intervention attachments , reports, progress, overview tabs

---

pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html

Attachments style fix

---

bower.json
pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html

Pl. visits seen as modif on save

---

pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/planned-visits.html
pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dissaggregations.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/mixins/repeatable-data-sets-mixin.html

on-iron-select related fixes

---

pmp/modules/app-modules/interventions/data/intervention-item-data.html
pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/planned-visits.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
pmp/modules/mixins/amendment-mode-mixin.html
pmp/modules/styles/file-styles.html

[ch5073]
- fix PD amendments add btn visibility 
- fix planned budget fields alignment

Polymer 2 migration fixes

---

pmp/modules/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

HF indicator

---

pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/mixins/list-filters-mixin.html

1. Go to reports list 
2. Add and populate all filters
3. Clean browser cache and indexedDB
4. Reload the list 
Result: Some filters appear as disabled
[ch5073]

Disabled filters on list reload issue

---

pmp/modules/app-modules/interventions/mixins/fr-numbers-consistency-mixin.html
pmp/modules/app-modules/interventions/pages/overview/components/fund-reservations-display.html
pmp/modules/app-modules/partners/pages/overview/partner-overview.html

Feature multi currency actuals errors

---

pmp/modules/app-modules/partners/pages/details/partner-details.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Relabel Basis for Risk rating

---

pmp/app-shell.html
pmp/modules/app-modules/agreements/agreements-module.html
pmp/modules/app-modules/agreements/components/agreement-status.html
pmp/modules/app-modules/agreements/data/agreement-item-data.html
pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/agreements/pages/details/components/agreement-amendments.html
pmp/modules/app-modules/interventions/components/intervention-status.html
pmp/modules/app-modules/interventions/data/intervention-item-data.html
pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/mixins/intervention-permissins-mixin.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/agreement-selector.html
pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/update-fr-numbers.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
pmp/modules/app-modules/partners/components/partner-status.html
pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/config/app-constants.html
pmp/modules/layout/components/etools-error-messages-box.html
pmp/modules/mixins/ie11-mixin.html
pmp/modules/mixins/pagination-mixin.html

[ch5287]
*This PR is not exhaustive

Extract app constants & resolve TODOs

---

pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/update-fr-numbers.html

Fix eager validation

---

pmp/modules/layout/components/countries-dropdown.html

Fixed issue with country dropdown not being scrollable
[ch5294]

Country selector scroll issue fix

---

pmp/modules/app-modules/partners/components/partner-status.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Fix fireEvent error on partner delete and type_of_assesment

---

pmp/modules/app-modules/agreements/components/agreement-status.html
pmp/modules/app-modules/interventions/components/intervention-status.html

Fixed an issue with "suspended" and "terminated" showing up as possible statuses in a draft agreement.
Also fixed an issue with blue icons for terminated or suspended PDs 
[ch5515]

Fix agreement status issues 

---

pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

fix(indicator dialog): means of verfification field editable [ch5662]

---

bower.json
pmp/modules/layout/page-header.html

Fix save user profile

---

pmp/modules/app-modules/partners/data/partner-item-data.html
pmp/modules/app-modules/partners/partners-module.html

delete partner fix

---

pmp/modules/app-modules/interventions/interventions-module.html

link partner name from PD details title to partner overview

---

pmp/modules/app-modules/interventions/pages/overview/components/monitoring-visits-list.html
pmp/modules/app-modules/interventions/pages/overview/intervention-overview.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/endpoints/endpoints.html

Display Programmatic Visits in Financial Assurance tab

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/app-modules/partners/pages/overview/partner-overview.html
pmp/modules/app-modules/partners/partners-module.html

[ch5446]
[ch5443]
[ch5449]
[ch5456]
[ch5445]

Financial Assurance label and columns changes

---

bower.json
pmp/app-shell.html

piwiki changes

---

pmp/modules/app-modules/interventions/pages/overview/components/monitoring-visits-list.html
pmp/modules/endpoints/endpoints.html

Update monitoring visits endpoint

---

bower.json
pmp/modules/layout/components/etools-cp-structure.html

Cp structure updates 

---

pmp/modules/layout/components/etools-cp-structure.html

Reset disabled Cps on PD change

---

pmp/modules/app-modules/agreements/data/agreement-item-data.html
pmp/modules/app-modules/agreements/pages/list/agreements-list.html
pmp/modules/app-modules/interventions/data/intervention-item-data.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/reporting-requirements-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/results/pd-lower-result-name.html
pmp/modules/app-modules/interventions/pages/details/components/results/result-cp-output-and-ram-indicators.html
pmp/modules/app-modules/partners/components/new-partner-dialog.html
pmp/modules/app-modules/partners/data/partner-item-data.html
pmp/modules/user/profile-operations-mixin.html

Fixes incorrect labels

---

pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/update-fr-numbers.html

FR number eager validations fix 

---

pmp/modules/app-modules/partners/data/partners-list-data.html
pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/config/app-constants.html
pmp/modules/redux/etools-data-redux-store.html
pmp/modules/static-common-data/mixins/dropdowns-static-data.html

Add Risk Rating filter

---

pmp/modules/app-modules/agreements/pages/list/agreements-list.html
pmp/modules/app-modules/interventions/data/interventions-list-data.html
pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/mixins/list-filters-mixin.html
pmp/modules/redux/etools-data-redux-store.html
pmp/modules/static-common-data/mixins/dropdowns-pmp-data.html

Feature  pd list grant and donor

---

.circleci/config.yml
bower.json

Add revision number to bower.json on build

---

pmp/modules/app-modules/interventions/data/interventions-list-data.html
pmp/modules/app-modules/interventions/pages/list/interventions-list.html

PD filters, grants and donors updates

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/config/app-constants.html
pmp/modules/endpoints/endpoints.html

 PD locations export button

---

.circleci/config.yml
bower.json

Add build date to bower.json

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/qpr-list.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html

reporting requirements fixes

---

pmp/modules/app-modules/interventions/pages/details/intervention-details.html

PD details - locations dropdown behavior fix, style improvement

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-cluster.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
pmp/modules/endpoints/endpoints.html
pmp/modules/layout/components/etools-cp-structure.html

Get HR cluster Rep. Requirements

---

bower.json
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/add-edit-special-rep-req.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/styles/reporting-requirements-lists-styles.html

Fix truncated calendar on IE

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

reordered assurance activities [ch5986] and relabeled programmatic visits from "Done" to "Completed" [ch5984]

assurance tab updates

---

bower.json
pmp/modules/layout/components/etools-single-file.html

downloadable files now open in a new tab [ch5156]

Open attachments in new tab

---

pmp/modules/toast-notifications/toast-notifications-mixin.html

Fixed an issue with toast messages not being visible in IE
[ch6019]

Fix missing toast message on IE 

---

pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html

fixed downloadable files on PD-attachments tab [ch5156]

Fix  downloadable files

---

pmp/modules/app-modules/reports/components/reports-display-list.html

Sync Reports list display to PRP

---

pmp/modules/app-modules/interventions/pages/details/intervention-details.html

Added partner vendor nr on PD details page

---

pmp/modules/layout/components/etools-cp-structure.html

Allow old CP selection on new agreement/pd

---

pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html

Preselect section and location on indicator

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
pmp/modules/layout/components/etools-single-file.html

Fix file upload issues

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Spot checks displayed values updates

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
pmp/modules/app-modules/interventions/pages/details/components/results/mixins/results-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/results/result-cp-output-and-ram-indicators.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

Allow RAM Indicators edit without using amendments

---

pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html

fix PD progress dates

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/app-modules/partners/pages/overview/partner-overview.html

update spot checks labels

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Financial assurance audits displayed values updates

---

pmp/modules/app-modules/reports/components/report-status.html
pmp/modules/app-modules/reports/components/reports-display-list.html
pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/mixins/list-filters-mixin.html

Reports list changes

---

bower.json
pmp/modules/styles/custom-iconsets/pmp-icons.html

Updates to etools-app-selector v2.0.1

---

pmp/modules/layout/page-header.html

Fixes typo in staging header

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/app-modules/partners/pages/overview/partner-overview.html

PD list reload fix after PD details were saved

---

pmp/modules/app-modules/interventions/pages/details/components/results/mixins/indicators-common-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

Fix allow null baseline

---

pmp/modules/app-modules/interventions/data/intervention-item-data.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

fix amendment types displayed by pd type

---

pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

Fix indicator eager validation

---

bower.json
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/hru-list.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html

Start date for HU Reporting Requirements

---

pmp/modules/app-modules/partners/pages/details/partner-details.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/layout/components/etools-form-element-wrapper.html
pmp/modules/mixins/risk-rating-mixin.html
pmp/modules/styles/risk-rating-styles.html

Feature  partner details updates

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Feature  update partners assurance [ch6462]

Feature  update partners assurance

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.html

- reset start date on open dialog/ edit start dt/ close/ open again

HU start date fixes

---

pmp/modules/app-modules/partners/pages/details/partner-details.html

updated vendor-number [ch5617]

updated vendor-number [ch5617]

---

pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html
pmp/modules/app-modules/partners/pages/details/components/staff-members.html
pmp/modules/app-modules/partners/pages/details/partner-details.html
pmp/modules/app-modules/partners/partners-module.html

Partner contacts redesign

---

pmp/modules/app-modules/agreements/components/agreement-status.html

Fix agreement status actions

---

pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html
pmp/modules/app-modules/partners/pages/details/components/staff-members.html

Partner contacts email readonly

---

pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html

placeholder fixes

---

pmp/modules/app-modules/agreements/agreements-module.html
pmp/modules/app-modules/agreements/pages/details/agreement-details.html

Special conditions PCA

---

pmp/modules/layout/menu/app-sidebar-menu.html

Updates 'information' link url on sidebar

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Risk rating bg color style fix

---

pmp/modules/app-modules/shared/components/monitoring-visits-list.html

Fix 'When' column data

---

pmp/modules/app-modules/shared/components/monitoring-visits-list.html

Rename When column

---

pmp/modules/app-modules/interventions/pages/details/components/planned-budget.html

fixed hidden status of the edit icon for planned budget

---

bower.json

Updates etools-profile-dropdown

---

pmp/modules/app-modules/agreements/agreements-module.html
pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/layout/components/year-dropdown.html

reference number year dropdown fixes

---

pmp/modules/app-modules/interventions/pages/details/components/grouped-locations-dialog.html
pmp/modules/endpoints/endpoints.html

Update locations endpoint

---

pmp/modules/styles/app-theme.html
pmp/modules/styles/risk-rating-styles.html

css fix for partner risk rating

---

pmp/modules/app-modules/partners/pages/details/partner-details.html
pmp/modules/app-modules/partners/partners-module.html

fix partner save error

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

fixed risk rating on partners assurance

---

pmp/modules/app-modules/interventions/pages/details/components/agreement-selector.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/layout/components/year-dropdown.html

Re-arrange PD fields

---

pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html

Remove signed by unicef auth officer chk

---

pmp/modules/app-modules/interventions/pages/list/interventions-list.html

Fix filtered by cp output export

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/layout/components/etools-cp-structure.html

ssfa agreement AO edit button added

---

pmp/modules/app-modules/interventions/pages/list/interventions-list.html

Fix pd export by country programme

---

pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html

Update Assessments&Assurance url

---

bower.json
pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
pmp/modules/app-modules/partners/pages/details/partner-details.html

* fix for some not showing borders on etools-data-table rows [ch6818]
* cvs style updates [ch6820]

Overall fixes

---

pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

Fix save PD (staging)

---

pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html

Fix save PD (dev)

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html

Fix In amendment mode not reflected correctly

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/layout/components/year-dropdown.html
pmp/modules/mixins/ajax-errors-parser-mixin.html
pmp/modules/styles/grid-layout-styles.html

Contingency PD activation

---

pmp/modules/app-modules/agreements/agreements-module.html
pmp/modules/app-modules/agreements/pages/details/agreement-details.html

Agreement attachment - use new upload endpoint

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html

Fix signed by unicef data source

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/generate-quarterly-reporting-requirements-mixin.html

Fix generate qpr

---

pmp/modules/app-modules/interventions/pages/details/components/planned-visits.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

Reinstate planned visits

---

pmp/modules/app-modules/reports/pages/summary/report-summary.html
pmp/modules/app-modules/reports/reports-module.html

Fix prp reports attachment

---

pmp/modules/app-modules/reports/pages/progress/components/disaggregations/table-content/one-disaggregation.html

Fix disaggregation display in reporting progress

---

pmp/modules/app-modules/interventions/components/pd-termination.html

PD termination fixes

---

pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

[ch2029]
[ch5745]
-use reporting_requirements instead of reporting_periods for permissions
-allow edit/add of special reporting requirements at all times
-condition add of reporting requirements by permissions also as before only edit was conditioned by permissions

Update Reporting Requirements permissions

---

pmp/app-shell.html
pmp/modules/app-modules/reports/mixins/report-details-mixin.html
pmp/modules/app-modules/reports/pages/summary/report-summary.html
pmp/modules/app-modules/reports/reports-module.html

Fix prp pages errors

---

pmp/modules/app-modules/reports/reports-module.html

rename Reporting Results tab to Results Reported

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html

rename AO field label to Partner AO

---

bower.json
pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/agreements/pages/list/agreements-list.html
pmp/modules/app-modules/interventions/pages/details/components/agreement-selector.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html
pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
pmp/modules/app-modules/partners/pages/details/partner-details.html
pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/mixins/list-filters-mixin.html
pmp/modules/styles/list-filter-styles.html

Lists filters updates

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/layout/components/year-dropdown.html

Fis year dropdown width

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/generate-quarterly-reporting-requirements-mixin.html

QPR generation updates

---

pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

Relabel to Quantity/Scale

---

pmp/modules/app-modules/reports/components/reports-display-list.html

Reports list displayed info updates

---

pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/redux/etools-data-redux-store.html

Report type filter

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/styles/reporting-requirements-lists-styles.html
pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html

QPR actions in modal always visible + HF indicator expand arrow bg update

---

pmp/modules/app-modules/reports/reports-module.html
pmp/modules/endpoints/endpoints.html

Update prp report actions, header & authenticate dw

---

index.html
pmp/app-shell.html
pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/mixins/module-routing-mixin.html
pmp/modules/app-modules/partners/partners-module.html
pmp/modules/app-modules/reports/reports-module.html

Module routing updates

---

pmp/modules/app-modules/mixins/module-routing-mixin.html
pmp/modules/app-modules/partners/partners-module.html
pmp/modules/app-modules/reports/pages/progress/report-progress.html
pmp/modules/endpoints/endpoints.html
pmp/modules/layout/components/etools-ram-indicators.html

[ch7208]
* Fix governments page stuck in loading state

New ram indicators component & governments list page load issue fix

---

index.html
pmp/app-shell.html
pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/app-modules/reports/components/report-status.html
pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
pmp/modules/layout/components/etools-progress-bar.html
pmp/modules/layout/components/etools-tabs.html
pmp/modules/layout/page-content-header/page-content-header.html
pmp/modules/styles/page-common-styles.html
pmp/modules/styles/page-layout-styles.html

PD progress print styles

---

pmp/modules/app-modules/reports/components/reports-display-list.html
pmp/modules/app-modules/reports/pages/list/reports-list.html

reports focal points

---

pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
pmp/modules/app-modules/reports/components/report-rating-dialog.html
pmp/modules/app-modules/reports/components/report-reject-dialog.html
pmp/modules/app-modules/reports/pages/progress/report-progress.html
pmp/modules/app-modules/reports/pages/summary/report-summary.html
pmp/modules/app-modules/reports/pages/summary/sent-bk-comments.html
pmp/modules/app-modules/reports/reports-module.html

Prp report display update

---

pmp/modules/app-modules/reports/pages/list/reports-list.html

Fix focal points param name for page reset observer

---

pmp/app-shell.html
pmp/modules/app-modules/mixins/module-routing-mixin.html
pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/app-modules/partners/partners-module.html

Fix partner routing issues

---

pmp/modules/app-modules/reports/reports-module.html
pmp/modules/endpoints/endpoints.html

Indicators export

---

pmp/modules/app-modules/reports/pages/summary/report-summary.html
pmp/modules/app-modules/reports/pages/summary/sent-bk-comments.html
pmp/modules/app-modules/reports/reports-module.html

Prp report tweaks

---

pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/layout/page-footer.html

PD progress updates

---

pmp/modules/app-modules/reports/components/reports-display-list.html
pmp/modules/layout/components/etools-single-file.html

[ch7783]
* new condition to prevent requesting reports without PD ID on PD reports page.

Fix report attachment field data reset on download

---

pmp/modules/app-modules/agreements/pages/list/agreements-list.html
pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/mixins/list-filters-mixin.html

Add always visible filters in filters menu

---

pmp/app-shell.html

Remove amendment mode ui in print mode

---

pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-table.html
pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
pmp/modules/app-modules/reports/pages/progress/report-progress.html
pmp/modules/app-modules/reports/pages/summary/report-summary.html

https://github.com/unicef/etools-partner-reporting-portal/issues/953

Prp report fixes 

---

pmp/modules/app-modules/reports/components/reports-display-list.html

Fix Reports filter issue

---

pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-table.html
pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
pmp/modules/app-modules/reports/pages/summary/report-summary.html
pmp/modules/layout/components/etools-ram-indicators.html

Fix intermittent 404 on get ram indicators

---

pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
pmp/modules/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.html

Update ratio indicator display

---

pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

Update fields visibility for contingency pd

---

pmp/modules/app-modules/agreements/pages/list/agreements-list.html
pmp/modules/app-modules/partners/pages/list/partners-list.html
pmp/modules/mixins/list-filters-mixin.html
pmp/modules/styles/list-filter-styles.html

Partners filters menu added

---

pmp/modules/app-modules/reports/pages/progress/components/indicator-details.html
pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
pmp/modules/app-modules/reports/pages/progress/report-progress.html
pmp/modules/mixins/utils-mixin.html

Update report progress values

---

pmp/modules/app-modules/agreements/data/agreement-item-data.html

Fix error Field(signed_amendment_attachment) - expects integer

Fix add agreement amendment error

---

pmp/modules/app-modules/partners/pages/overview/partner-overview.html
pmp/modules/styles/risk-rating-styles.html

Update risk rating style

---

pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
pmp/modules/mixins/utils-mixin.html

Tweak progress values display

---

bower.json
pmp/modules/app-modules/agreements/agreements-module.html
pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
pmp/modules/styles/required-field-styles.html

Use etools-upload for Agr./Signed Agreement att.

---

pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html

[ch6586]
Issue: 
* shoudn't we rename `internal_prc_review` to something that ends in `_attachment` like all the other fields used for file upload?
* if I send the `internal_prc_review=null` i get a validation error and I have to remove it from req payload before firing the request.

PD amendments upload functionality updates

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

[ch6586]
*Issue - can't bring PD to Signed status

Use etools-upload component for PD/Activation Letter

---

pmp/modules/app-modules/interventions/components/pd-termination.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

PD termination notice updated to new upload functionality

---

pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html

[ch8219] fixed signed pd validation

fixed sign pd validation

---

pmp/modules/mixins/list-filters-mixin.html

fixed issue when navigating from agreements list to partners list [ch8276]

Fix  console error navigation

---

pmp/modules/app-modules/partners/pages/list/partners-list.html

reset search filter

---

pmp/modules/app-modules/reports/pages/list/reports-list.html
pmp/modules/layout/components/data-refresh-dialog.html
pmp/modules/user/user-data-mixin.html

Fix reports filters on data reset

---

pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/styles/list-filter-styles.html

fixed pd filter list styles on IE [ch8082]

fixed pd filter list styles for IE

---

index.html
pmp/modules/layout/menu/app-sidebar-menu.html

replaces userVoice with Zendesk widget

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html
pmp/modules/app-modules/agreements/pages/details/components/amendments/agreement-amendments.html

fixed edit-mode property [ch8389]

Fix  agreements edit mode

---

pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

Updates to ratio indicator denominator

---

pmp/modules/app-modules/agreements/pages/list/agreements-list.html

adjusted the agreements landing page [ch7538]

adjusted the agreements landing page

---

pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html

Hide Disaggregation label for cluster indicator

---

pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html

 Prepopulate target denominator for ratio cluster indicator

---

pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html

Fix baseline negative number

---

pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/layout/components/etools-progress-bar.html

Fix intervention-progress target display

---

pmp/modules/app-modules/reports/pages/progress/components/indicator-details.html
pmp/modules/mixins/utils-mixin.html

Update Location progress display

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/details/intervention-details.html

PD save fix for ref year

---

pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html

fixed missing required symbol for signed date on pd add amendment dialog [ch8445]

fixed missing required symbol on signed date field

---

pmp/modules/app-modules/partners/partners-module.html

Fix existing partner assessments updates

---

pmp/modules/app-modules/reports/reports-module.html

fixed export button style [ch8510]

fixed export button style

---

pmp/modules/app-modules/agreements/data/agreements-list-data.html
pmp/modules/app-modules/interventions/data/interventions-list-data.html
pmp/modules/app-modules/partners/data/partners-list-data.html

Handle indexeddb DatabaseClosedError

---

pmp/modules/app-modules/agreements/pages/details/agreement-details.html

fixed issue with delete button not showing up after uploading a file[ch8601]

Fix  show delete button

---

pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html

fixed position required field on partner contacts dialog [ch8440]

fixed position required field on partner contacts dialog

---

pmp/modules/layout/components/data-refresh-dialog.html

No upload warning on refresh data

---

pmp/modules/app-modules/interventions/pages/details/components/planned-budget.html

fixed planned budget alignment issues [ch8561]

Fix  planned budget aligment

---

pmp/modules/app-modules/agreements/data/agreements-list-data.html
pmp/modules/app-modules/interventions/data/interventions-list-data.html
pmp/modules/app-modules/partners/data/partners-list-data.html

Edge fix on country changed in another browser

---

pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html

fixed intervention validation [ch8599]

fixed intervention validation

---

pmp/modules/app-modules/settings/components/add-disaggregation-dialog.html
pmp/modules/app-modules/settings/components/disaggregation-list.html
pmp/modules/endpoints/endpoints.html
pmp/modules/mixins/frontend-pagination-mixin.html
pmp/modules/redux/etools-data-redux-store.html
pmp/modules/static-common-data/static-common-data.html

added search input for disaggregations and active toggle button [ch7351]

added search input for disaggregations and a toggle switch for active

---

pmp/modules/layout/components/etools-status/etools-action-button.html

fixed info-icon click issue [ch8684]

fixed info button click issue

---

pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
pmp/modules/styles/required-field-styles.html

Cluster indicator fixes

---

pmp/app-shell.html
pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
pmp/modules/mixins/uploads-mixin.html

Reset upload flags on del assessment

---

pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dissaggregations.html

fixed disaggregations dropdown on add indicator dialog [ch8403]

Fix  disaggreg dropdown

---

pmp/modules/app-modules/interventions/interventions-module.html
pmp/modules/app-modules/interventions/pages/attachments/components/attachment-dialog.html
pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html
pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
pmp/modules/app-modules/partners/pages/details/components/staff-members.html
pmp/modules/endpoints/endpoints.html
pmp/modules/styles/etools-cp-header-actions-bar-styles.html

PD attachments redesign

---

pmp/modules/app-modules/interventions/pages/details/components/results/result-link-lower-results.html

Edge style fix for expected results

---

pmp/modules/app-modules/interventions/pages/list/interventions-list.html
pmp/modules/app-modules/partners/pages/details/partner-details.html
pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
pmp/modules/app-modules/partners/pages/overview/partner-overview.html
pmp/modules/mixins/risk-rating-mixin.html

Fix edge style issue on partner pages

---

pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/mixins/date-mixin.html

Fix progress-bar value not shown in Edge

---

bower.json
pmp/modules/app-modules/partners/pages/details/components/staff-members.html
pmp/modules/layout/components/data-refresh-dialog.html

Update etools-behaviors version

---

pmp/modules/app-modules/partners/pages/details/components/staff-members.html

Fix partner contacts display in Edge

---

pmp/modules/app-modules/interventions/pages/details/components/planned-visits.html
pmp/modules/app-modules/interventions/pages/overview/components/fund-reservations-display.html
pmp/modules/app-modules/reports/pages/progress/report-progress.html
pmp/modules/layout/components/etools-form-element-wrapper.html
pmp/modules/layout/components/etools-status/etools-status.html

Edge fix for dynamically applying css classes

---

pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
pmp/modules/mixins/date-mixin.html

Fix date comparison

---

pmp/modules/app-modules/settings/components/disaggregation-list.html
pmp/modules/redux/etools-data-redux-store.html
pmp/modules/styles/app-theme.html

Active toogle& search on disaggreg list fixes

---

pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html

Fix readonly state for cash field on planned budget
