- pmp/app-elements/partners/partner-details.html
- pmp/pages/page-partners.html
@adi130987 Previously you were stamping a `partner-data` in both details and overview. This is just a small tweak to instead stamp one `partner-data` in `page-partners` and bind the partner down into details and overview. And I removed the relevant redundancies that followed the change.
> Page data refactor

- pmp/app-elements/partners/partners-list.html
- pmp/pages/page-partners.html
Previously text-content was used to bind to the selection
value for fields like partner-type. This is less flexible
and also created problems in firefox/IE with empty text-nodes.
Adding name attributes to the dropdowns and selecting based on that
fixes this.
Also small style update to the list in page-partners. List should not
have the same layout that partners-details and overview do. Now it's
centered on the page.
> Partners-list and partners-page tweaks

- pmp/app-behaviors/common-general-behavior.html
Parse fix for attachment filename displayed.
> fix(filename display): attachment file names parser fix

- pmp/app-behaviors/common-general-behavior.html
- pmp/app-elements/governments/government-details.html
- pmp/pages/page-governments.html
You can now refresh details/add new government in simple page without errors.
> fix(government-details): Refreshing details/add new page now works

- pmp/app-elements/partners/partner-details.html
- Show  field Core Values Assesments for partners with csoType equal to Academic Institution or Community Based Organization also
- connects unicef/etools-issues#157
> Core values assesments: show field for other partners also

- pmp/app-elements/interventions/intervention-details.html
- pmp/app-elements/interventions/intervention-form/agreement-selector.html
- Fix for 'Partner Organization' not being populated with the selected value after page refresh on Edge
- Fix for 'Agreement' not being populated after page refresh on Edge
- Fix for 'Partner focal points' not having a selected value on page refresh sometimes and when navigating from one intervention with a set Partner focal point to another intervention with a set Partner focal point
> Intervention details Edge fixes

- pmp/app-elements/agreements/agreement-details.html
- connects unicef/etools-issues#584
- fixed a " Missing ':' " error on ie 11
> feature(fix-ie11-colon-issue):

- pmp/pages/page-agreements.html
- connects unicef/etools-issues#589
- fixed a error with the add button not appearing on the agreements page
> Fix partner error 

- Dockerfile
- Dockerfile-dev
connects unicef/etools-issues#592
The issue is related to https://github.com/unicef/etools-infra/pull/21. 
As far as i can see, the PMP container is based on Alpine Linux, which does not have bash installed by default, so **fab ssh:pmp** does not work anymore. This issue may exist for other submodules too.
The fix requires the docker machine to be recreated.
EDIT
fix typo **fab ssh:backend** -> **fab ssh:pmp**
> add bash to the docker dependencies

- pmp/app-elements/countries-dropdown/countries-dropdown.html
- connects unicef/etools-issues#341
- App Wrapper -> Country name should be aligned right next to down arrow. Country dropdown list box should be max-height: 380px
> Update countries dropdown style

- pmp/app-elements/agreements/agreement-amendments.html
- pmp/app-elements/agreements/agreement-details.html
- pmp/app-elements/partners/partner-overview.html
- pmp/app-menu/app-sidebar-menu.html
- styles/page-layout-styles.html
* remove `im` from agreement details
* agreement details template download btn width changed to 220px
* community links (menu) opened in new tab
* page title font weight changed to normal
* partner overview: hide partnerships columns header if there are no partnerships to display
> Overall fixes

- pmp/app-elements/interventions/intervention-overview.html
-fixed an issue with sector labels overflowing out of their container on the interventions overview page
- connects unicef/etools-issues#669
> Fix intervention overview overflowing sectors

- pmp/app-elements/interventions/intervention-details.html
Fixed an issue on te PD details page, document type was empty after page reload
connects to unicef/etools-issues#695
> Fix pd document type

- pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
- pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html
- pmp/app-elements/interventions/intervention-planned-budget.html
* add fr numbers: amount validation was skiped because intervention frs list is empty
* renamed `_checkFrsConsistency` to `_checkFrsAmountConsistency` because `_checkFrsConsistency` is already in frs consistency behavior and is different
> Fix frs amounts validation on add

- pmp/app-behaviors/ie11-behavior.html
- fixed an issue with the loading overlay not covering the entire page on IE11
- connects unicef/etools-issues#716
> Fix IE11 loading overlay 

- pmp/app-elements/interventions/intervention-status.html
- added the missing 'Closed' status on ended interventions 
- connects unicef/etools-issues#740
> Add missing closed status 

- pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
- pmp/app-elements/interventions/interventions-list.html
- fr warnings were appearing on the list if a draft did not have inter. dates set yet
- connects unicef/etools-issues#761
> Fix PD list FR errors on draft

- pmp/app-elements/agreements/generate-PCA-dialog.html
- removed the arabic option from the generate pca dialog
- connects unicef/etools-issues#754
> Remove arabic from generate PCA dialog 

- pmp/app-elements/interventions/intervention-details.html
- removed add indicator button from new pd page
- connects unicef/etools-issues#885
> Fix add indicator btn on new pd page

- pmp/app-config/app-user-permissions-behavior.html
- fixed an issue with missing permissions on the PD details page
- connects unicef/etools-issues#901
> Fix pd attachment permissions issue

- pmp/app-elements/agreements/agreement-amendments.html
- agreement ammendments can now show declared legacy ammendment types even when they're not in the static data
- connects unicef/etools-issues#915
> Agreement Amendments CP extension 

- styles/page-layout-styles.html
- footer was overlaping elements on ie11
- connects unicef/etools-issues#1136
> Fix footer responsive issues

- pmp/modules/app-modules/interventions/mixins/intervention-page-tabs-mixin.html
- pmp/modules/app-modules/mixins/module-common-mixin.html
[ch5073]
- Shared Partners modification made in Partner Details  is not updated in Partners List if after modification user hits save and then back from browser(Partner Details is expanded all times)
- ADD NEW PD/SSFA shows all tabs from PD/SSFA Details, if a PD/SSFA Details is open, click on PD/SSFA and ADD NEW PD/SSFA(when you try to open OVERVIEW/REPORTS/PROGRESS  enters in continue loading process)
> fix: refresh list data after item was saved & new PD tabs

- pmp/modules/app-modules/interventions/pages/overview/components/monitoring-visits-list.html
- pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
- pmp/modules/app-modules/partners/pages/overview/partner-overview.html
- pmp/modules/endpoints/endpoints.html
[ch6127]
[ch6137]
`/api/t2f/travels/activities/<%=id%>/?year=<%=year%>&status=completed` status param is ignored right now... wait for BE changes.
> Partner assurance tab updates

- pmp/modules/app-modules/agreements/agreements-module.html
- pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
this is against: feature--reference-number-rework
backend:
https://github.com/unicef/etools/pull/1725
> enable fields

- pmp/modules/app-modules/partners/data/partner-item-data.html
- pmp/modules/app-modules/partners/pages/details/components/edit-core-values-assessment.html
- pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
- pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
- pmp/modules/app-modules/partners/partners-module.html
[ch6586] - partner assessments attachments using new upload functionality
BE is not working:
* if I use `assessment.report` property I get the error:
```
report: ["The submitted data was not a file. Check the encoding type on the form."]
```
* but we should not use `assessment.report` and use instead `assessment.report_attachment` to keep consistency
> partner assessments attachments updates to use new upload component

- pmp/modules/app-modules/agreements/agreements-module.html
- pmp/modules/app-modules/agreements/data/agreement-item-data.html
- pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
- pmp/modules/app-modules/agreements/pages/details/components/amendments/agreement-amendments.html
- pmp/modules/app-modules/partners/data/partner-item-data.html
- pmp/modules/app-modules/partners/pages/details/components/edit-core-values-assessment.html
- pmp/modules/app-modules/partners/pages/details/partner-details.html
- pmp/modules/styles/required-field-styles.html
[ch6586] - partner file uploads updates
BE issues:
* Core Values Assessments upload not working, no error on save request, but it's not returning uploaded file url in `attachment` property as it should.
* Partner assessments upload(new property used: `report_attachment`) has issues on save with the old upload properties `report` and `report_file`. It returns 400 errors `No file was submitted` if I remove old upload properties from request payload or if I keep them and `report` property is not a file.
> Partners new upload component integration

- pmp/app-shell.html
[ch8362] [ch8432] - fix issue: `from reports list open reset data dialog and select "Agreements". Result: data is refreshed but the page remains in loading and is displaying only reports list title even the url is for agreements list page`
> fix update path method to avoid triggering route change events twice

- src_ts/components/layout/etools-progress-bar.ts
[ch18523] Progress bar percentage number should go beyond 100%, the bar color should be filled 100%
> [ch18523] Progress bar percentage number should go beyond 100%, the bar color should be filled 100%

- src_ts/components/app-modules/interventions/components/intervention-status.ts
[ch20798] Global Save btn from Attachments tab, for Ended and Closed PD is not needed anymore
> [ch20798] Global Save btn from Attachments tab, for Ended and Closed PD is not needed anymore

- src_ts/components/app-modules/interventions/data/interventions-list-data.ts
[CH21870] Contingency PDs should display in List when filter toggle is off
> [CH21870] Contingency PDs should display in List when filter toggle is off

- src_ts/components/app-shell/header/page-header.ts
[ch27249] Dropdown option for Ro translations (used for testing) to not be available on prod
> [ch27249] Dropdown option for Ro translations (used for testing) to not be available on prod

- src_ts/components/app-shell/header/data-refresh-dialog.ts
[ch31456] REFRESH DATA button should not close pop up window if no checkbox is selected
> [ch31456] REFRESH DATA button should not close pop up window if no checkbox is selected

- src_ts/components/app-shell/header/countries-dropdown.ts
[ch32097] Countries dropdown doesn't go to item that starts with the pressed letter
>  [ch32097] Countries dropdown doesn't go to item that starts with the pressed letter

- src_ts/components/pages/partners/data/partners-list-data.ts
[ch32552] On countries that have no items, the lists remain in perpetual loading
> [ch32552] On countries that have no items, the lists remain in perpetual loading

- src_ts/components/app-shell/header/page-header.ts
if the ro language does not exist and we're not in dev the first language gets spliced out.
> remove custom function for ro language

- src_ts/components/pages/reports/reports-module.ts
[ch33773] Previous report details displayed when opening another report
> [ch33773] Previous report details displayed when opening another report

- .circleci/config.yml
- src_ts/components/pages/partners/data/partner-item-data.ts
- src_ts/components/pages/partners/partners-module.ts
[ch33814] After importing a partner from vision, he is not available in the list for creating a new agreement
> [ch33814] After importing a partner from vision, he is not available in the list for creating a new agreement
